### ISSUE TITLE
Nové nástroje ve validátoru 2.1

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/komplexni-validator#101]
Dobry den,
rad bych se zeptal, jake verze nove pridanych nastroju z uvedenych odkazu v Instalaci se maji instalovat do validatoru v. 2.1.?
Jsou to tyto?
MP3val:  Download MP3val 0.1.8 binaries for Windows (frontend version 0.1.1 included) (130 Kb)
shntool: 3.0.10? Ke stazeni pouzit Source nebo Win32?
Checkmate: mp3checker-0.21.exe?
 
Dekuji

A.D.

**Comment by godnat** [comment]
Dobrý den, 

tyto nové nástroje jsou pro kontrolu balíčků s digitalizáty gramodesek. Jejich funkčnost ještě testujeme, nicméně to vypadá že kontrola validnosti formátu běží správně, kontrolu konkrétních vlastností zvukových souborů ještě budeme ladit. 

Pro jejich zapojení do validátoru instalujete tyto verze: 

MP3val     Download MP3val 0.1.8 binaries for Windows (frontend version 0.1.1 included) (130 Kb)
shntool verze pro Win32
Checkmate mp3checker-0.21.exe

Doplníme do dokumentace nástroje.

**Comment by Drahotussky** [comment]
Gramodesky nedigitalizujeme. Neni tedy pro nas nutne tyto nastroje do validatoru instalovat?

**Comment by godnat** [comment]
Určitě ne, tyto nové nástroje jsou jen pro soubory mp3 a WAV.

**Comment by jbil7** [comment]
Popis nástrojů v dokumentaci doplněn. Issue proto uzavírám.
