### ISSUE TITLE
Validátor hlásí příliš velký kompresní poměr u některých obrazů komprimovaných ztrátově

### ISSUE THREAD

**Issue by godnat** [NLCR/komplexni-validator#106]
Komplexní validátor hlásí chybu, je-li u některých obrazů vysoká komprese. Validátor kontroluje kompresní poměr a očekává kompresi 1:6 až 1:35. Prázdné stránky ale mohou mít zřejmě kompresní poměr i přes 1:100 přestože příkazový řádek zadává kompresi 1:20. 
Zřejmě se tedy nejedná o chybu obrazu. Prověříme. 
V Komplexním validátoru zvětšíme pravděpodobně rozsah povoleného kompresního poměru.

**Comment by godnat** [comment]
Kontrola kompresního poměru u uživatelských kopií prozatím zrušena. Vyskytují se obrazy, které i se zadáním doporučených příkazových řádků jsou komprimovány mnohonásobně více. Jsou to obrazy, které zřejmě obsahují jen dvě barvy, tj bitonální- což může asi vzniknout i tím, že původní skenovaný obraz je bitonální, tj. ne nastavením skeneru (např. přeexpozice). Bude se dále prověřovat.

**Comment by rzeh4n** [comment]
Nechal jsem tam ale kontrolu na minimální kompresní poměr, to by i ty prázdné stránky splňovat měly.
