### ISSUE TITLE
Jpylyzer vrací error Počet barevných komponent: hodnota "4" neodpovídá žádnému z omezení: [musí být přesně '1',musí být přesně '3'] 

### ISSUE THREAD

**Issue by isenkyr** [NLCR/komplexni-validator#108]
Dobrý den, 
komplexní validátor verze 2.1 mi vrací chybu u MC checkBinaryFilesValidByExternalUtil: Počet barevných komponent: hodnota "4" neodpovídá žádnému z omezení: [musí být přesně '1',musí být přesně '3']. Pro konverzi používám nástroj kakadu s konverzními parametry dostupnými na https://www.ndk.cz/standardy-digitalizace/standardy-pro-obrazova-data ("Cblk={64,64}" Corder=RPCL "Stiles={4096,4096}" "Cprecincts={256,256},{256,256},{128,128}" ORGtparts=R Creversible=yes Clayers=1 Clevels=5 "Cmodes={BYPASS}" Cuse_sop=yes Cuse_eph=yes)

Chci se zeptat jak upravit konverzní parametry aby validátor nehlásil chybu? Anebo jde o špatné nastavení validátoru? Jako přílohu přikládám zdrojový i výstupní soubor.
[Soubory.zip](https://github.com/NLCR/komplexni-validator/files/3696695/Soubory.zip)

**Comment by isenkyr** [comment]
Dobrý den,
na problém jsem již přišel. Vstupní obrázek je ve formátu ARGB a nikoliv pouze ve formátu RGB. Omlouvám se za zybtečné issue.

I.Šenkýř

**Comment by godnat** [comment]
Dobrý den, 

ano je to tak, obrazy obsahují navíc Alfa kanál a takový obraz pak není 24bitový (3 komponenty) ale 32 bitový (4 komponenty). 
Issue není zbytečné, občas se s tím u obrazů setkáváme, takže výhledově by toto mohlo přijít do nějakých FAQ.
