### ISSUE TITLE
DCMD_PAGE_XXXX: /oai_dc:dc: nenalezen očekávaný povinný element 'dc:coverage'

### ISSUE THREAD

**Issue by volodymyrdn** [NLCR/komplexni-validator#109]
Dobrý den,

při validaci METS, obsahující MODS a DC pro jednotlivé strany, validátor zahlásil chybu: 

> DCMD_PAGE_0001: /oai_dc:dc: nenalezen očekávaný povinný element 'dc:coverage'

Podle standardu (https://www.ndk.cz/standardy-digitalizace/dmf_monografie_1-3-2 str.č.74), **dc:coverage** vychází z elementu **start**, který je sice povinný, ale spadá pod nepovinný element **part**, který v MODSu není. Prosím o vyjádření, kde je chyba? Ve standardu, nebo ve validátorovi?
Předem děkuji.

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
máte pravdu, validátor by túto chybu hlásiť nemal. Element mods:start, z ktorého sa dc:coverage tvorí,  síce povinný je, ale len v prípade, ak je v zázname prítomný element mods:extent, ktorého subelementom mods:start je.

**Comment by rzeh4n** [comment]
Opraveno pro všechny relevantní verze DMF (monografie 1.3, 1.3.1, 1.3.2 a periodika 1.7, 1.7.1).  Bude součástí verze následující aktuální 2.1.1.
