### ISSUE TITLE
Chybové hlášení v bibliografických metadatech a OCR u balicku, které na poprve prosly validaci

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/komplexni-validator#110]
Dobry den,
narazili jsme na tento problem. Minuly tyden nam validaci prochazely balicky periodika. Nyni nam validator u dalsich balicku tehoz periodika zacal hlasit stejnou chybu  v bibliografických metadatech titulu a issue + jeste chybu u OCR.
Zkusili jsme udelat novou validaci u balicku,ktere prosly validaci a objevila se u nich taky dana chyba. 
Jedna se o tato chybova hlaseni:

1) **checkBibliographicMetadataMatchProfile: záznam MODSMD_TITLE_0001 není validní podle  mods_3.6.xsd: src-resolve: Cannot resolve the name 'xml:lang' to a(n) 'attribute declaration' component.**

Stejne hlaseni je i u bibliografickych dat u ISSUES

2) **obsah souboru D:\digi_linka\Uloziste\ose309-0003lr\alto\alto_ose309-0003lr_0156.xml není validní podle Xml schema ze souboru C:\Users\Admin\AppData\Local\KomplexniValidatorGUI\app\validatorConfig\fDMF\periodical_1.7.1\xsd\alto_2.0.xsd: src-resolve: Cannot resolve the name 'xlink:simpleLink' to a(n) 'attribute group' component.**

Jeden balicek ke stazeni: https://www.uschovna.cz/zasilka/UCYZ8PEKT4953PZL-IXM/JBRS7T434D

Muzete nam prosim poradit, v cem je problem?

**Comment by Drahotussky** [comment]
Tak dnes už validator nehlasi chybu stale stejneho balicku.
Za zjisteni priciny bych nicmene byl rad.

Dekuji

**Comment by rzeh4n** [comment]
Souviselo to s výpadkem v Library of Congress (#117) a s importy ze url přes http (#127)
