### ISSUE TITLE
Periodika 1.8

### ISSUE THREAD

**Issue by mhalva** [NLCR/komplexni-validator#112]
Validátor 2.1 neumožní provedení validace PSP balíku, který byl vytvořen nejnovějším ProArcem. "Chyba: Není definována fDMF pro Periodika 1.8"

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
áno, chyba sa objavila, pretože zatiaľ validátor nebol upravený podľa najnovších DMF (monografie 1.4, periodiká 1.8). Výhľadovo by sa tak malo stať v priebehu tohoto roku.

**Comment by mhalva** [comment]
Děkuji za dobrou zprávu. Současný validátor 2.1 už je téměř rok starý (z dubna 2019)...

**Comment by mhalva** [comment]
Dobrý den, nová verze validátoru 2.1.1 z května 2020 také neobsahuje DMF pro monografie 1.4 a periodika 1.8... :-(
