### ISSUE TITLE
Verze validatoru 2.1.1

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/komplexni-validator#115]
Dobry den,
upravou metadatovych profilu se rozumi, ze validator validuje i balicky vytvorene podle aktualnich standardu 1.8 pro perio a 1.4 pro mono?

Dekuji

A. Drahotussky

**Comment by godnat** [comment]
Dobrý den,

v této verzi validátoru byly opraveny některé chyby reportované v issues. Validátor zatím neumí validovat podle nejnovějších standardů (tj. perio 1.8 a mono 1.4), k úpravě validátoru pro nejnovější verze standardu dojde ještě v letošním roce.

**Comment by mhalva** [comment]
Projekty digitalizace jsou už zase v plném proudu. Kdy bude prosím možné validovat PSP balíčky podle aktuálních standardů 1.8 a 1.4?
