### ISSUE TITLE
ERROR u nejnovější verze nástroje JHOVE

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/komplexni-validator#116]
Dobry den,
aktualizoval jsem validator i s jednotlivými externími nástroji az na Jpylyzer,ktery se mi nepovedlo ve validatoru nastavit
Nástroj Jhove ukazal chyby,ktere se ve verzi nastroje 1.16.7 neobjevovaly.
[2020_06_08_09_25_21_osa001-0010r1.txt](https://github.com/NLCR/komplexni-validator/files/4746201/2020_06_08_09_25_21_osa001-0010r1.txt)

Jde o chybu validatoru?

dekuji

**Comment by rzeh4n** [comment]
Prosím o vyzkoušení s JHOVE 1.29. Starší verze již nejsou poporované (od Validátoru 2.4)
https://github.com/NLCR/komplexni-validator/wiki/Instalace#jhove

**Comment by jbil7** [comment]
Testováno s JHOVE 1.28 (latest-release). K výše hlášeným chybám zde již nedochází.

Děkuji, zde uzavírám.
