### ISSUE TITLE
Error: checkBibliographicMetadataMatchProfile: záznam MODSMD_TITLE_0001 není validní podle  mods_3.6.xsd: Premature end of file.

### ISSUE THREAD

**Issue by isenkyr** [NLCR/komplexni-validator#117]
Dobrý den,

dnes jsem spustil validaci Komplexním validátorem NK verze 2.1.1 a dostal jsem následné chybové hlášení.
Error: checkBibliographicMetadataMatchProfile: záznam MODSMD_TITLE_0001 není validní podle  mods_3.6.xsd: Premature end of file.
Toto chybové hlášení se objevuje pro všechny MODS uvedené v hlavním METS. Divné je to, že validaci balíčku jsem prováděl někdy před 14 dny stejnou verzí komplexního validátoru a vše proběhlo v pořádku. Prosím o prověření. Jako přílohu přikládám hlavní METS.
[mets_osa001-0010rd.zip](https://github.com/NLCR/komplexni-validator/files/4916993/mets_osa001-0010rd.zip)

**Comment by godnat** [comment]
Dobrý den,

stále zjišťujeme co se děje, ale nebude to chyba balíčku aani validátoru, protože i při našem testu balíčky, které dříve prošly nyní neprocházejí. Vypadá to ale, že procházejí balíčky, které maji mods 3.5 a 3.4. . Může to souviset s URI odkazy v xmlns, došlo zřejmě k nějaké změně ve zdrojích Library of Congress.

**Comment by godnat** [comment]
Máme podezření, že výše uvedené chování by mohlo být způsobeno přechodem z http na https na straně Kongresové knihovny a validátor se tak nemůže odkázat na potřebný zdroj. Bude upraveno v další verzi nástroje, validátor už nyní obsahuje potřebné zdroje, ale v jednom případě používá odkaz na web Kongresové knihovny, ten odkaz bude tedy přesměrován na lokálně stažený zdroj. Než vyjde nová verze validátoru, nasdílíme návod k opravě (případně přímo opravené soubory) na vašich lokálních instalacích.

**Comment by godnat** [comment]
Chyba se již nevyskytuje, zřejmě byla na straně LOC odstraněna.
