### ISSUE TITLE
ERROR: MODSMD_VOLUME_0001: /mods:mods/mods:physicalDescription/mods:form[0]/@authority: hodnota 'rdacarrier' , tdamedia

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/komplexni-validator#119]
Dobry den,
pri validaci balicku ve verzi 2.1.1 nam vyskocila nize uvedena chyba. Prijde mi, ze zaznam knihy je v poradku (viz prilozeny mets). Stejnou chybu vyhodily i verze 2.0 a 2.1, ale u jineho balicku, ktery ma stejne hodnoty nam v unoru unoru 2020 probehla validace bez chyb.
ERROR: MODSMD_VOLUME_0001: /mods:mods/mods:physicalDescription/mods:form[0]/@authority: hodnota 'rdacarrier' nesplňuje žádnou ze specifikací ["marcform","marccategory","marcsmd","gmd"]
	ERROR: MODSMD_VOLUME_0001: /mods:mods/mods:physicalDescription/mods:form[1]/@authority: hodnota 'rdamedia' nesplňuje žádnou ze specifikací ["marcform","marccategory","marcsmd","gmd"]
[mets_ope301-00028e.zip](https://github.com/NLCR/komplexni-validator/files/5055237/mets_ope301-00028e.zip)

Muzete nam prosim poradit, v cem je problem?
Dekuji

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
podľa priloženého mets usudzujem, že celý záznam má byť v RDA (v mods:originInfo používate atribút eventType ktorý je prípustný len u záznamov v RDA; a rovnako použitie hodnôt atribútu authority elementu mods:form tak ako ich používate vo vašom zázname je prípustné len pri záznamoch v RDA). Chyba validácie pochádza pravdepodobne z toho, že na úrovni VOLUME máte element mods:descriptionStandard uvedený dvakrát, raz s hodnotou aacr, raz s hodnotou rda. Validátor preto validoval podľa prvej hodnoty, aacr (kedy hodnoty "rdamedia" a "rdacarrier" zmieneného atribútu povolené nie sú).
