### ISSUE TITLE
Element ObjectCategory v PREMISO

### ISSUE THREAD

**Issue by volodymyrdn** [NLCR/komplexni-validator#122]
Dobrý den,

Zpracovávám projekt Monografie podle standardu 1.0. Při validování projektu dostavám chybu validátoru:

**Chyba:amd_mets_ex001-0000ml_0001.xml: OBJ_001: /mets:techMD/mets:mdWrap/mets:xmlData/premis:object: nenalezen očekávaný povinný element 'premis:objectCategory'**

Když ten element ale přidám, tak dostávám následující chybu:

**Chyba:checkPremisIsValidByXsd: amd_mets_ex001-0000ml_0001.xml: OBJ_001: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"info:lc/xmlns/premis-v2":objectCategory}'. One of '{"info:lc/xmlns/premis-v2":objectIdentifier, "info:lc/xmlns/premis-v2":preservationLevel, "info:lc/xmlns/premis-v2":significantProperties, "info:lc/xmlns/premis-v2":objectCharacteristics}' is expected.**

Podle https://old.ndk.cz/standardy-digitalizace/DMFmonografie10.pdf, str.č. 44, element ObjectCategory je povinný.

Podle https://www.loc.gov/standards/premis/v2/premis-2-1.pdf, str.č. 25, element objectCategory je povinný. Ale ve schema je vynechán: https://www.loc.gov/standards/premis/v2/premis-v2-1.xsd

Mohli byste mi poradit, co z toho je správně, a jak se to dá vyřešit?
Předem děkuji. 

S pozdravem 
Volodymyr Dyshchyn

**Comment by godnat** [comment]
Dobrý den,

element objectCategory v PREMIS v balíčcích vynechejte. 
Vypadá to, že se jedná o rozpor v samotném PREMIS. V minulosti byl element ze standardu vyškrtnut jako nevalidní (viz https://old.ndk.cz/standardy-digitalizace/seznam-zmen_monografie_1.0-1.1.2) a zjistili jsme, že data, která v úložišti máme a jsou dle DMF Monografie 1.0 tento element také mají vynechaný.

**Comment by volodymyrdn** [comment]
Dobrý den, 

děkují za odpověď.
V případě že element ObjectCategory vynecháme z PREMISO, validátor hlásí chybu: 

_/mets:techMD/mets:mdWrap/mets:xmlData/premis:object: nenalezen očekávaný povinný element 'premis:objectCategory'_

Tak že, je to chyba validátoru, a tím pádem můžeme ji taky ignorovat? 
Děkuji.

S pozdravem 
Volodymyr Dyshchyn

**Comment by godnat** [comment]
Dobrý den,

chybu ve validátoru ignorujte, do příští verze nalidátoru to opravíme.
