### ISSUE TITLE
ERROR: mods:mods/mods:physicalDescription/mods:form[0]: nenalezen povinný atribut 'type'

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/komplexni-validator#124]
Dobry den,
pri validaci ve validatoru 2.1.1 nam vyskocila chyba pri validaci hudebniny. Jde o knihu, ktera ma zaznam zpracovany dle aacr2.
V elementu physicalDescription je zapis takto: 
    **form authority="marcform">print</form
    form authority="gmd">hudebnina</form
    extent>1 klavírní výtah (290 s.) ; 28 cm</extent****

U jinych knih, kde je pouze zapis **form authority="marcform">print</form** nedochazi k hlaseni chyby.
Prikladam zaznam knihy z metadatoveho editoru a log z validatoru
[2021_03_23_12_50_54_eed4be6c-cc27-44ee-927c-e4ca1eb40751.zip](https://github.com/NLCR/komplexni-validator/files/6189435/2021_03_23_12_50_54_eed4be6c-cc27-44ee-927c-e4ca1eb40751.zip)
 [cnb001889433_VOLUME.zip](https://github.com/NLCR/komplexni-validator/files/6189412/cnb001889433_VOLUME.zip)

Take jsme narazili na knihu (hudebninu), ktera je zpracovana dle RDA a v elementu  physicalDescription se vyskytuje zápis
**form authority="rdacarrier" type="carrier">svazek</form
    form authority="rdamedia" type="media">bez média</form
  form authority="marcform">print</form**

Pri validaci pak validator opet ocekava atribut type.
U klasicke monografie, ktera ma take zaznam dle RDA se takova chyba ale neukaze.

Dekuji za nazor a pomoc

Drahotussky

**Comment by MirkaBenackova** [comment]
Dobrý deň, 
ďakujeme za upozornenie na nezrovnalosť vo validátore. 
V oboch vami spomínaných príkladoch máte dáta v poriadku a vyplnené správne. Validátor mal v tomto prípade nastavenú povinnosť M u atribútu type všeobecne, pritom v niektorých prípadoch sa tento atribút nepoužíva. Povinnosť sme znížili a platné to bude od nasledujúcej verzie validátoru.

**Comment by FilipPavcik** [comment]
Issue zatváram, keďže je vyriešené vo validatore od verzie 2.2.
