### ISSUE TITLE
Attribut @type v elementu checksum v info.xml

### ISSUE THREAD

**Issue by isenkyr** [NLCR/komplexni-validator#129]
Dobrý den,

dnes jsem si stáhl Komplexní validátor v2.2 a všiml jsem si varování **obsah souboru D:\AAA\aaa\hka001-000v4u\info_hka001-000v4u.xml není validní podle Xml schema ze souboru D:\VisualStudio\Programs\SiriusMETS\Tools\GeneralValidatorNdkForm\Tools\KV_CLI-v2.2\validatorConfig\fDMF\periodical_1.8\xsd\info_per1.8.xsd: cvc-pattern-valid: Value 'md5' is not facet-valid with respect to pattern 'MD5' for type 'checksumType'.** Ve standardu (periodika 1.8, monografie 1.4) je ale uvedena hodnota **md5** Je to jen taková drobnost, ale asi by bylo dobré to sjednotit.
![obrazek](https://user-images.githubusercontent.com/19608475/138053198-846d0296-60e4-44bc-ac78-1f91cb1b448e.png)

**Comment by PavlinaKocisova** [comment]
Zdravím, díky za připomínku, bude opraveno v nadcházejících verzích standardu monografie 2.0 a periodika 1.9
