### ISSUE TITLE
Neuložení/nezobrazení výsledku validace v textovém logu

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/komplexni-validator#130]
Dobry den,
nainstalovali jsme novy validator a zkusili validaci, ale log se neulozil v slozce log. Ta se zachovala po odinstalovani predchozi verze validatoru.
Ani v samotne aplikaci validatoru nejde pres funkci Zobrazit spustit vysledek validace v textovem logu nebo XML logu.
Díval jsem se do Nápovedy o aplikaci, kde je uvedena cesta k souborům logs. Ta ale po instalaci neexistovala, musel jsem ji vytvorit,ale ani poté se tam log neuloží. Prikladam snímek s cestou
V predchozi verzi validatoru cesta ta logy odkazovala primo do slozky,kde je umisten validator.

Dekuji za radu

![Validatror](https://user-images.githubusercontent.com/6399737/140284212-15e6423d-e3ea-467e-894c-d81c00bdb43e.jpg)

**Comment by jbil7** [comment]
Dobrý den,
@Drahotussky, dle mých zjištění zůstala v konfiguračním souboru cesta, která byla nejspíše užívána při vývoji (viz Váš screenshot, "Adresář s logy") a která nefunguje, neboť ve složce c:\Users nelze vytvářet/mazat adresáře bez administrátorských práv. Tuto cestu je potřeba ručně změnit v souboru `$VALIDATOR_HOME\app\config.properties` na Vámi užívanou cestu (např. onen adresář zachovaný od předchozí verze), a sice přepsáním hodnoty u proměnné `validation.log_dir`. Před speciální znaky `: \` je nutno vložit escape znak `\`.

@rzeh4n, prosím, bylo by možné toto opravit, aby cesta k logům byla nakonfigurována správně již po instalaci bez nutnosti zásahu, jako tomu bylo u předchozích verzí? Děkuji!
