### ISSUE TITLE
Validátor verze 2.2.1 - datum/čas podle ISO 8601

### ISSUE THREAD

**Issue by isenkyr** [NLCR/komplexni-validator#132]
Dobrý den,

včera jsem si všiml, že byla zveřejněna další verze Komplexního validátoru v.2.2.1. Verzi jsem otestoval a dostal chybové hlášení mets_vsg001-0000yf.xml: /mets:mets/mets:metsHdr/@LASTMODDATE: hodnota '2021-09-22T12:07:54' nesplňuje žádnou ze specifikací [regulární výraz '^(?<year>[0-9]{4})(?<month>1[0-2]|0[1-9])(?<day>3[01]|0[1-9]|[12][0-9])T(?<hour>2[0-3]|[01][0-9])(?<minute>[0-5][0-9])(?<second>[0-5][0-9](.(?<millis>[0-9]{3}))?)?(?<timezone>Z|[+-](2[0-3]|[01][0-9])([0-5][0-9])?)$',regulární výraz '^(?<year>[0-9]{4})-(?<month>1[0-2]|0[1-9])-(?<day>3[01]|0[1-9]|[12][0-9])T(?<hour>2[0-3]|[01][0-9]):(?<minute>[0-5][0-9])(:(?<second>[0-5][0-9])(.(?<millis>[0-9]{3}))?)?(?<timezone>Z|[+-](2[0-3]|[01][0-9])(:([0-5][0-9])?)?)$']

Z uvedeného mi plyne, že součástí datumu má být také časové pásmo, čemuž rozumím. Problém bych, ale viděl v tom že standard toto přesně nedefinuje. Současně také nedošlo k žádné úpravě ve standardu a mění se validační pravidla. Dále pak co s ostatními datumy, které nemají ve standardu explicitně definovanou časovou zónu, ale mají být podle normy ISO8601, např. mods:recordCreationDate, mets:file[@created], info.xml element created a další?

Děkuji I.Šenkýř

**Comment by FilipPavcik** [comment]
Dobrý deň,

máte pravdu, je to tak ako píšete. Štandard presne nestanovuje v rámci dátumu časovú zónu a dátumy by mali byť uvádzané podľa normy ISO8601. (V METS hlavičke na úroveň vteřin.)

@rzeh4n Bolo by možné to upraviť? Ďakujem.

**Comment by jbil7** [comment]
Domnívám se, že chyba by se dala opravit, a sice v souboru `$VALIDATOR_HOME/validatorConfig/fDMF/$DMF_VERSION/metsProfiles/primary_mets_header.xml` vždy u druhého `regexp` (pro _extended format_) přidat otazník mezi dolar a kulatou závorku na konci regexu:

```
<regexp>^(?&lt;year&gt;[0-9]{4})-(?&lt;month&gt;1[0-2]|0[1-9])-(?&lt;day&gt;3[01]|0[1-9]|[12][0-9])T(?&lt;hour&gt;2[0-3]|[01][0-9]):(?&lt;minute&gt;[0-5][0-9])(:(?&lt;second&gt;[0-5][0-9])(.(?&lt;millis&gt;[0-9]{3}))?)?(?&lt;timezone&gt;Z|[+-](2[0-3]|[01][0-9])(:([0-5][0-9])?)?)?$</regexp>
```
Tímto zásahem se bude se skupinou timezone pracovat jako s nepovinnou.

**Comment by rzeh4n** [comment]
dávno opraveno

**Comment by jbil7** [comment]
Problém v novém release 2.3 pořád trvá, viz např.: fDMF pro [mono v.2.0](https://github.com/NLCR/komplexni-validator/blob/1055915f78a8acb22bd8504c16461c377341f979/sharedModule/src/main/resources/nkp/pspValidator/shared/validatorConfig/fDMF/monograph_2.0/metsProfiles/primary_mets_header.xml#L63), [mono v.1.4](https://github.com/NLCR/komplexni-validator/blob/1055915f78a8acb22bd8504c16461c377341f979/sharedModule/src/main/resources/nkp/pspValidator/shared/validatorConfig/fDMF/monograph_1.4/metsProfiles/primary_mets_header.xml#L53), [perio v.1.8](https://github.com/NLCR/komplexni-validator/blob/1055915f78a8acb22bd8504c16461c377341f979/sharedModule/src/main/resources/nkp/pspValidator/shared/validatorConfig/fDMF/periodical_1.8/metsProfiles/primary_mets_header.xml#L53) atd.

Z toho důvodu issue znovu otevírám.

**Comment by rzeh4n** [comment]
Opravil jsem, kde to jeste zustalo v bb40ac9968fee12d59ba14195a2e81697cb447c6

**Comment by jbil7** [comment]
Uzavírám jako opravené.
