### ISSUE TITLE
Validace formátu identifikátorů

### ISSUE THREAD

**Issue by jbil7** [NLCR/komplexni-validator#136]
Dobrý den,
rád bych otevřel otázku, zda by bylo možné do validátoru implementovat validaci identifikátorů předepsaných v DMF, u nichž je definován/očekáván jednoznačný formát na základě standardu. Jedná se například o uuid, urn:nbn, ččnb, issn...

**Comment by rzeh4n** [comment]
pro uuid a urn:nbn doplněno už dříve

**Comment by rzeh4n** [comment]
issn se (pro dmf mon-2.0 a per-1.9) kontroluje regulérním výrazem (přidáno v d2c1098bd055103b4702f281cfbd6fd6e942c5da), mohlo by se doplnit o výpočet kontrolního součtu..
