### ISSUE TITLE
Revize povinnosti elementů v MIX_001 (původní sken)

### ISSUE THREAD

**Issue by jbil7** [NLCR/komplexni-validator#138]
V aktuální verzi validátoru (2.2.3), v profilech mix_ps.xml (tedy pro validaci metadat **MIX_001**), u několika elementů nesouhlasí nastavená povinnost (atribut `mandatory`) oproti povinnosti uvedené DMF. Kontroloval jsem zatím nejaktuálnější DMF pro textové digitalizáty (monografie v. 1.4 a periodika v. 1.8), kde se jedná o tyto elementy:

- iccProfile
- iccProfileName
- iccProfileVersion
- sourceIDType
- ScannerCapture
- scannerManufacturer
- ScannerModel
- scannerModelName
- scannerModelNumber
- scannerModelSerialNo
- MaximumOpticalResolution
- xOpticalResolution
- yOpticalResolution
- opticalResolutionUnit
- scannerSensor
- ScanningSystemSoftware
- scanningSoftwareName
- scanningSoftwareVersionNo
- digitalCameraManufacturer
- digitalCameraModel
- digitalCameraModelName
- digitalCameraModelNumber
- digitalCameraModelSerialNo
- cameraSensor
- CameraCaptureSettings
- samplingFrequencyUnit
- //xSamplingFrequency/numerator
- //xSamplingFrequency/denominator
- //ySamplingFrequency/numerator
- //ySamplingFrequency/denominator

U všech výše uvedených případů je nastaven atribut `mandatory` na hodnotu **false**, přičemž by dle DMF měla být ve všech uvedených případech **true**.

Prosím proto o revizi nastavení povinnosti u technických metadat.

**Comment by rzeh4n** [comment]
opraveno v 917c8c2bd82ddd5ce8886a48525bed81aaf22ac9 a 917c8c2bd82ddd5ce8886a48525bed81aaf22ac9, jen pro poslední verze DMF Monografie-2.0 a Periodika-1.9

**Comment by FilipPavcik** [comment]
Dobrý deň, 

nastavené povinnosti by sme potrebovali opraviť aj pri starších verziách DMF, keďže aj staršie verzie DMF sa ešte stále používajú. Issue preto otváram znovu.

**Comment by jbil7** [comment]
V commitu 57fe63422c57d2a9bccd2357470db6c3bd1cad43 jsem provedl revizi nastavených povinnosti dceřiných elementů v MIX_001 napříč všemi verzemi fDMF, které ještě nebyly v souladu s papírovým DMF. Nyní by již vše mělo být 1:1. Jedná se o:

- fDMF perio 1.4
- fDMF perio 1.6
- fDMF perio 1.7
- fDMF perio 1.7.1
- fDMF perio 1.8
- fDMF mono 1.0
- fDMF mono 1.2
- fDMF mono 1.3
- fDMF mono 1.3.1
- fDMF mono 1.3.2
- fDMF mono 1.4

Potvrzuji, že v nejnovějších fDMF, tj. perio 1.9, 2.0 a mono 2.0, 2.1 byla provedena revize v rámci commitu b4cb8ce070ac1948f27f8fce8a4869b6f973f8d4 , tudíž zde jsou nastavené povinnosti v pořádku.

U všech verzí textových digitalizátů se v papírovém DMF vyskytuje problém s povinností elementu `mix:ScannerCapture`, který by měl správně být nepovinný. Více viz https://github.com/NLCR/Standard_NDK/issues/186. Z toho důvodu nastavuji povinnost ve všech verzích u `mix:ScannerCapture` na nepovinnou a to navzdory znění papírového DMF.

Zároveň jsem provedl revizi nastavených povinností v MIX_001 i u všech zvukových digitalizátů:

- fDMF gramo 0.3
- fDMF gramo 0.4
- fDMF gramo 0.5
- fDMF fono 0.3

V papírových DMF pro gramodesky verze 0.3 a 0.4 se vyskytuje rozpor vůči XSD pro MIX, a sice v názvu elementu `digitalCameraCapture`, který by správně měl být `DigitalCameraCapture`. Co se týče této chyby v fDMF, v gramodeskách v. 0.4 to bylo opravené, ve v. 0.3 jsem to opravil nyní. Zbylé případy by měly být v pořádku.

**Comment by jbil7** [comment]
Uzavírám jako zrevidované a opravené.
