### ISSUE TITLE
Chyba parsování xml

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/komplexni-validator#139]
Dobrý den,
validator 2.2.1., nástroj Jhove (1.14.6 a 1.16) nam pri validaci ukazuje tento ERROR:
ERROR: checkBinaryFilesValidByExternalUtil: chyba parsování xml (výstup nástroje JHOVE): Premature end of file. 

Neni to nami vytvoreny balicek. Nami vytvorene balicky projdou validatorem.

V cem je problem? 
Odkaz na jeden balicek:
https://www.uschovna.cz/zasilka/DUATJSJ8VSYW8KN4-XBN/

**Comment by jbil7** [comment]
Momentálně jsem narazil na tento problém a pravděpodobně se týká kódování některých znaků, které se nacházejí v adrese balíčku. Pokud se v adrese nachází písmenka s diakritikou (ěščřžýáíé atd.), jpylyzer i jhove vyhodí chybu. V níže uvedeném případě je chyba rekonstruována s jpylyzerem. Problematický je zde název adresáře **testovací složka**.

```
C:\Users\nekdo\myApps\jpylyzer_1-18>jpylyzer "c:\Users\nekdo\Desktop\tmp\testovací složka\abc123-000jzi\usercopy\uc_abc123-000jzi_0001.jp2"
Traceback (most recent call last):
  File "cli.py", line 8, in <module>
  File "jpylyzer\jpylyzer.py", line 706, in main
  File "jpylyzer\jpylyzer.py", line 600, in checkFiles
  File "jpylyzer\jpylyzer.py", line 483, in findFiles
UnicodeDecodeError: 'utf8' codec can't decode byte 0xed in position 39: invalid continuation byte
Failed to execute script cli
```

V návaznosti na to KV ohlásí chybu "Premature end of file".

S obsahem balíčku (vč. obrázků) tato chyba nemá dle mého zjištění nic společného. Po přesunu mimo "testovací složku" chyba zmizí.

**Comment by jbil7** [comment]
Ještě bych dodal, že jhove starší verze (v mém případě 1.16) má problém i s mezerou v názvu adresáře:

```
C:\Users\nekdo\myApps\jhove-1-16>jhove.bat "c:\Users\nekdo\Desktop\tmp\testovaci slozka\abc123-000jzi\usercopy\uc_abc123-000jzi_0001.jp2"
slozka\abc123-000jzi\usercopy\uc_abc123-000jzi_0001.jp2""=="" was unexpected at this time.
```

Totéž jsem zkoušel s jhove v. 1.24 a tomu už mezera v názvu adresáře nevadí.

**Comment by rzeh4n** [comment]
Prosím o otestování s JHOVE 1.29. Starší verze již nejsou poporované (od Validátoru 2.4)
https://github.com/NLCR/komplexni-validator/wiki/Instalace#jhove

**Comment by jbil7** [comment]
Zkoušeno s JPYLYZER 2.2 a JHOVE 1.28 (latest-release) na balíčku uloženém v adresáři `c:\nkp\tmp\příliš žluťoučký kůň úpěl ďábelské ódy\` (tj. název obsahuje mezery i diakritiku). Problémy se již nevyskytují - validátor XML výpisy z externích nástrojů v pořádku přebírá.

Děkuji, zde uzavírám.
