### ISSUE TITLE
checkBibliographicMetadataMatchProfile: záznam MODSMD_VOLUME_0001 není validní podle  mods_3.6.xsd: cvc-complex-type.2.4.a

### ISSUE THREAD

**Issue by Zeman-Jan** [NLCR/komplexni-validator#141]
Dobrý den,

při validování balíku vícesvazkové monografie, komplexní validátor 2.2.1 ukazuje error v bibliografických metadatech typu BIBLIOGRAPHIC_METADATA_MATCH_PROFILE_VOLUME :

checkBibliographicMetadataMatchProfile: záznam MODSMD_VOLUME_0001 není validní podle  mods_3.6.xsd: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.loc.gov/mods/v3":physicalLocation}'. One of '{"http://www.loc.gov/mods/v3":url, "http://www.loc.gov/mods/v3":holdingSimple, "http://www.loc.gov/mods/v3":holdingExternal}' is expected.

Mohu poprosit o radu, v čem by mohla být chyba? Ve standardu je pro element location definován physicalLocation a shelfLocator jako mandatorní položka.
Přikládám screen z validátoru a soubor mets.

Děkuji.

![image](https://user-images.githubusercontent.com/124141303/216011748-93741b82-dcd3-406e-a611-8e5d4e3b9c0f.png)
[mets_ex001-0003fo.zip](https://github.com/NLCR/komplexni-validator/files/10555759/mets_ex001-0003fo.zip)

**Comment by FilipPavcik** [comment]
Dobrý deň,

myslím, že v tomto prípade je chyba v poradí elementov. Za top elementom `location` by mali nasledovať subelementy v tomto poradí: `physicalLocation`, `shelfLocator`, `url`. Vy máte subelement `url` na prvom mieste, tak zrejme preto Vám vyhadzuje chybu. 

Vo verzii DMF v. 1.4, ktorú ste zrejme využívali, sme to mali chybne uvedené a ešte sme to nemali zoradené v správnom poradí. Ale v najnovšom DMF v. 2.0 už máme poradie elementov zoradené správne, podľa medzinárodného štandardu MODS.
