### ISSUE TITLE
Standard 1.9/P - Element physicalDescription - form (rda/aacr2)

### ISSUE THREAD

**Issue by okaucky** [NLCR/komplexni-validator#142]
Dobry den, prosim o radu jak postupovat v pripade, ze chceme vytvorit vnitrni cast pro vyse uvedeny standard. 

1) Element form ma pro rodicovske entity (titul a priloha) specifikovanou aacr2 a rda variantu.
2) Element form lze vytvorit i pro rodice (vnitrni cast) - specifikace pro vnitrni cast obsahuje vyrazne kratsi popis nez pro entity z bodu 1).
3) Element form pro vnitrni cast, obsahuje jen aacr2 popis.

Dotazy:
Jak se zachovat, kdyz budeme vytvaret balicek typu rda, do ktereho budeme chtit pridat vnitrni casti? Muzeme vytvorit balicek ,ktery bude podle aktualniho standardu castecne rda a castecne aacr2? Pokud ne, prosim o doplneni jak by mel vypadat element physicalDescription-form pro vnitrni casti v pripade, ze rodicovske entity (jsou typu rda).

Dekuji za pomoc.
S pozdravem OK

**Comment by FilipPavcik** [comment]
Dobrý deň,

konzultoval som Vašu otázku aj s kolegami a ako najvhodnejšie sa nám javí vyplnit daný element rovnakým sposobom ako je to definované na úrovni TITLE. Teda pre element `form` môžete použiť predpis pre záznamy v RDA z titulovej úrovne aj na vnitřní část. 

Zároveň se nám ale zdá element `form` na úrovni vnitřní části ako nadbytečný a do budoucna budeme uvažovať nad odstranením tohto elementu z danej úrovne.
