### ISSUE TITLE
Monografie a Periodika - vnitrni casti: <dc:coverage>???</dc:coverage>

### ISSUE THREAD

**Issue by okaucky** [NLCR/komplexni-validator#145]
Dobry den, prosim o vysvetleni v jakem formatu a jakou hodnotu vyplnovat do dc:coverage pro vnitrni casti. dc:coverage ma prebirat hodnotu z mods elementu: start/end. 

V mods pro vnitrni cast bude 2x start a 2x end ~ potomci elementu part extent (jednou pro pageIndex a jednou pro pageNumber). 

ref. https://old.ndk.cz/standardy-digitalizace/monografie20_final.pdf 
strana 94

 Je zadouci, aby sekce dc obsahovala 4 duplicitni elementy <dc:coverage>???/dc:coverage ?

Pozorovany problem: Neni mozne rozeznat, co hodnoty prislusnych elementu reprezentuji. 

Priklad:
//page index???
dc:coverage1/dc:coverage
dc:coverage2/dc:coverage
//page number??? 
dc:coverage2/dc:coverage
dc:coverage3/dc:coverage
nebo
//page index???
dc:coverage1/dc:coverage
//page number??? 
dc:coverage2/dc:coverage
//page index???
dc:coverage2/dc:coverage
//page number??? 
dc:coverage3/dc:coverage
...

Otazky: 
1) Zalezi na poradi elementu?
 2) Skutecne mame vytvaret pro vnitrni cast 4x element dc:coverage???/dc:coverage ?
 *3) Pokud ne, prosim o popis jak dc:coverage???/dc:coverage spravne vyplnit, diky za pomoc.

S pozdravem OKaucky

**Comment by FilipPavcik** [comment]
Dobrý den,

při vyplňování `dc:coverage` doporučujeme dodržovat aktuální standardy, a tedy vytvářet elementy `dc:coverage` 4-krát (tj. 2x pro `start` a 2x pro `end)`. 

Problému na který poukazujete jsme si vědomi, avšak stávající podoba zápisu uvedená ve standardu se nám momentálně jeví jako nejlepší řešení.

Poradí elementů doporučujeme dodržovat tak, jak to máte uvedené v první variantě, tedy hodnoty z elementů `start` a `end`, které patří k sobě, by měli jít za sebou. 

Protože se však issue netýká Komplexního validátoru, ale spíš standardů NDK, tak issue zavírám a kopíruji ho na Github standardů NDK.
