### ISSUE TITLE
Problémy při instalaci Komplexního validátoru 

### ISSUE THREAD

**Issue by FilipPavcik** [NLCR/komplexni-validator#147]
Při instalaci Komplexního validátoru verze 2.3 (avšak platí to i pro starší verze validátoru - např. jsem zkoušel i verzi 2.2.1) se objeví chybová hláška od Windows Defender, která brání instalaci nástroje. 

Samozřejmě je to možné obejít a vynutit si instalaci, avšak bylo by možné se na to podívat a opravit to? 

Vďaka.

Přikládám i printscreen:

![hlaska](https://github.com/NLCR/komplexni-validator/assets/86611996/4b0f3246-a5c7-4cf0-86c8-3a685a143eae)

**Comment by jbil7** [comment]
Problém se znovu objevuje i u Windows 11. Pokud je institucionální politika nastavena restriktivněji, validátor nelze nainstalovat, případně ani stáhnout z GitHubu. Z toho důvodu issue otevírám. 

Podpisy aplikované počínaje verzí validátoru 2.6.1 nemají na reputaci ve SmartScreen filtru vliv. Důvodem může být [ECC](https://en.wikipedia.org/wiki/Elliptic-curve_cryptography) veřejný podpis, který [dle vyjádření Microsoftu](https://learn.microsoft.com/en-us/windows/apps/develop/smart-app-control/code-signing-for-smart-app-control) není ve SmartScreen filtru podporovaný.
