### ISSUE TITLE
Kontrola formatRegistryName v amd_mets souborech

### ISSUE THREAD

**Issue by jbil7** [NLCR/komplexni-validator#148]
Definice metadatových formátů NK předepisují použití registru formátů PRONOM, který má být uveden v elementu `premis:formatRegistryName` ([viz např. DMF pro perio v. 1.8, s. 67](https://standardy.ndk.cz/ndk/standardy-digitalizace/copy_of_DMFperiodika_18_final.pdf)). Hodnota PRONOM se však ve formalizovaných DMF Komplexního validátoru pro tento element nehlídá, [viz např. zde, ř. 168](https://github.com/NLCR/komplexni-validator/blob/master/sharedModule/src/main/resources/nkp/pspValidator/shared/validatorConfig/fDMF/periodical_1.8/techProfiles/premis_object_ps.xml). 

Bylo by prosím možné validační profily opravit tak, aby byla hodnota v elementu kontrolována?
Děkuji!

**Comment by rzeh4n** [comment]
doplněno ve verzi 2.4.1

**Comment by jbil7** [comment]
Úspěšně otestováno v CLI verzi 2.4.1 na linuxové platformě. Do všech souborů `premis_object_*.xml` v dotčených verzích fDMF byla povinná hodnota doplněna.

Děkuji, uzavírám jako vyřešené.
