### ISSUE TITLE
Warning u typu strany sheetMusic

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/komplexni-validator#149]
Dobrý den,
validátor 2.2.1 hlásí při validaci Warning u typu strany sheet**M**usic. Požaduje výraz sheet**m**usic. 
V pravidlech popisu je ale uvedena hodnota sheet**M**usic.

**Comment by FilipPavcik** [comment]
Dobrý deň,
ak Vám ukazuje warning, tak sa nejedná o chybu, ale len o upozornění... Ale je to tak, ako píšete. Správne sa má hodnota zapisovať s veľkým písmenom "sheetMusic", tak ako je to popsané v aktuálnych Pravidlech pro popis monografií verze 2.2. 

Avšak neviem, ktorú verziu DMF ste používali. Ak ste používali ešte staršiu verziu (_DMF pro monografie 1.4_), tak tam je hodnota uvedená nesprávne s malým písmenom. Správne však má byť hodnota zapísaná s veľkým písmenom ako „sheetMusic“, tak ako je to v Pravidlech pro popis.

**Comment by jbil7** [comment]
Do v. 1.4 v DMF pro monografie panovala nekonzistence `sheetMusic` / `sheetmusic` s Pravidly pro popis. Od v. 2.0 je v DMF pro monografie pouze odkaz do Pravidel pro popis, kde je uvedena hodnota `sheetMusic`. 

Z toho důvodu bude opraveno následovně:

Do v. 1.4 bude povolen typ strany: `sheetmusic` i `sheetMusic`.
Od v. 2.0 bude povolen typ strany: `sheetMusic`, druhá možnost nikoli.

**Comment by jbil7** [comment]
Uzavírám jako opravené.
