### ISSUE TITLE
Validování balíčků podle aktuálních standardů validátorem 2.3

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/komplexni-validator#152]
Dobrý den,
rád bych se zeptal, zda je možné použít současný validátor verze 2.3 pro validování balíčků vytvořených podle aktuálních standardů? Validátor oficiálně validuje balíčky se standardy o jednu verzi nižší.
Zkusil jsem udělat validaci balíčku monografie podle aktuálních standardů 2.1. oproti standardům 2.0. Je takový výstup alespoň nějak relevantní? Nebo se kontrola balíčku podle aktuálních standardů musí dělat ručně oproti standardům?
Jaká je Vaše praxe?

Děkuji

**Comment by jbil7** [comment]
Dobrý den, validace balíčků s vyšší verzí (2.1) než současná verze validátoru podporuje (2.0) je technicky možná, neboť mezi těmito verzemi nejsou natolik velké změny, aby validátoru bránily v provádění jednotlivých kontrol (změny názvosloví souborů atd.) Metodicky se ovšem nejedná o vhodné řešení a nelze jej doporučit pro nasazení na produkci. V každém případě je nutné všechny výsledky z validátoru považovat za orientační a posuzovat je s ohledem na změnový list dané vyšší verze standardu. Změnový list pro DMF monografií v. 2.1 je k dispozici [zde](https://standardy.ndk.cz/ndk/standardy-digitalizace/Zmenovy_list_DMF_monografie.pdf).

**Comment by Drahotussky** [comment]
Rád bych upozornil, že při validaci balíčku monografie (standard 2.1) ve validátoru 2.3 nedošlo u vnitřní části k nahlášení chybějícího atributu **type** u elementu part. Tento atribut je i u předchozí verze standardu monografie (2.0), ale nevím, jestli u ní validátor hlásí chybu.
Naopak se objevil ERROR u technických metadat, že chybí povinný element  **premis:linkingEventIdentifier** u OBJ_002, což je MC. Tento element by ale měl být jen u OBJ_001, což je TIFF. Je to tak?
Přikládám výstup z validátoru
[2023_10_04_08_04_49_a409d1b2-646a-4aa9-a353-4d9648a21e3a.txt](https://github.com/NLCR/komplexni-validator/files/12890853/2023_10_04_08_04_49_a409d1b2-646a-4aa9-a353-4d9648a21e3a.txt)

**Comment by jbil7** [comment]
Ano, máte pravdu. Dle DMF pro monografie v. 2.0 by element `premis:linkingEventIdentifier` v objektu pro masterCopy být vynucován neměl. Jedná se patrně o chybnou konfiguraci validátoru. Založil jsem k tomu issue #154.

**Comment by jbil7** [comment]
Ohledně elementu `mods:part`, děkujeme za upozornění. Kontroloval jsem nastavení validátoru vůči DMF pro monografie v. 2.0 a atribut `type` by vskutku měl být povinný. Založil jsem k tomu issue #155.

**Comment by jbil7** [comment]
Validátor v. 2.4.1 validuje balíčky dle nejnovějšího standardu, tj. mono v. 2.1 i perio v. 2.0. 

Z toho důvodu zde uzavírám.
