### ISSUE TITLE
Nenastavená povinnost u atributu type pro element mods:part na úrovni strany

### ISSUE THREAD

**Issue by jbil7** [NLCR/komplexni-validator#155]
Komplexní validátor při validaci nevynucuje přítomnost atributu `type` v elementu `mods:part[./mods:detail[@type="pageNumber"]]` na úrovni strany. Atribut je ovšem dle DMF povinný (viz např. [DMF pro monografie v. 2.0, s. 104](https://standardy.ndk.cz/ndk/standardy-digitalizace/copy_of_monografie20_final.pdf)). Problém byl zjištěn u monografie v. 2.0, avšak na základě letmého průzkumu více fDMF se týká nejspíše více verzí.

Příčinou je, že ve fDMF chybí na příslušném místě (např. [zde](https://github.com/NLCR/komplexni-validator/blob/1055915f78a8acb22bd8504c16461c377341f979/sharedModule/src/main/resources/nkp/pspValidator/shared/validatorConfig/fDMF/monograph_2.0/biblioProfiles/mods/page_rda.xml#L73C44-L73C44)) nastavení povinnosti pomocí atributu `mandatory`.

**Comment by fremrovaK** [comment]
Dále budeme řešit v rámci rozvoje a úprav DMF. Zde uzavírám a issue přesouvám na [GH Standardu NDK.](https://github.com/NLCR/Standard_NDK/issues/217)
