### ISSUE TITLE
Nenastavená povinnost u atributu type pro element mods:part na úrovni vnitřní části (kapitoly) monografie

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/komplexni-validator#158]
Dobrý den,
při validaci balíčku monografie (standard 2.1) ve validátoru 2.3 nedošlo u **vnitřní části (kapitoly)** k nahlášení chybějícího atributu type u elementu part. Tento atribut je i u předchozí verze standardu monografie (2.0), ale nevím, jestli u ní validátor hlásí chybu.
Hlásil jsem to již u https://github.com/NLCR/komplexni-validator/issues/152 , vzniklo z toho issue pro nenastavenou povinnost u atributu type pro element mods:part **na úrovni strany**

**Comment by jbil7** [comment]
Aktuálně validátor při absenci ohlásí pouze varování o nečekaném elementu `mods:part`. Důvodem je to, že ve validačních profilech pro kapitoly je element hledán pomocí predikátu `@type='pageNumber'`, nebo `@type='pageIndex'`. Pakliže atribut `@type` není obsažen, element `mods:part` předepsaný dle DMF validátor vůbec nenajde, přičemž chybu neohlásí, neboť je MA.

Z toho důvodu je nejprve nutné vyhledat jakýkoli `mods:part` a zkontrolovat, zda obsahuje atribut `@type`. Až v dalším kroku se má testovat dceřiná struktura pod `mods:part`. 

Totéž se týká i starších DMF (mono 1.4 a perio 1.8), kde se elementy `mods:part` vyhledávají pomocí predikátu `mods:detail[@type='pageIndex']`. Ani přítomnost `mods:detail[@type='pageIndex']` není předem zkontrolována.

Bude opraveno.

**Comment by jbil7** [comment]
Uzavírám jako opravené.
