### ISSUE TITLE
Chybí základní informace ke kompilaci nástroje

### ISSUE THREAD

**Issue by borivoj-tydlitat** [NLCR/komplexni-validator#160]
Dobrý den,
můj první pokus (uznávám, že naivní, nejsem javista) o kompilaci Komplexního validátoru na Fedora Linuxu FC39 skončil s různými chybami v závislosti na použité verzi JDK a Gradle (v gradle/wrapper/gradle-wrapper.properties). Prosím, je možno doplnit projekt o elementární informaci o tom, s jakou verzí JDK, případně dalšího potřebného software, by měl projekt kompilovat?

**Comment by jbil7** [comment]
Základní informace ke kompilaci byly doplněny do wiki dokumentace: https://github.com/NLCR/komplexni-validator/wiki/Build

V dokumentaci je psáno, že pro build je nutná java 21, nicméně dle mých zkušeností postačuje na verzi Komplexního validátoru 2.4.1 a 2.4.2 i java 17. Důležité je mít v rámci javy k dispozici i knihovnu javafx (stejné verze). 

OpenJDK vč. JavaFX lze stáhnout například zde: https://bell-sw.com/pages/downloads/#jdk-17-lts  (Full JDK).

Issue zde v tuto chvíli uzavírám.

**Comment by borivoj-tydlitat** [comment]
Děkuji. Jen drobnost: v https://github.com/NLCR/komplexni-validator/wiki/Build#build-aplikace-do-climodule-verzejar má asi být 
`java -jar modules/cliModule/build/libs/cliModule-2.4.2.jar`.
