### ISSUE TITLE
Dotaz k nové verzi validátoru validující díla dle aktuálních standardů

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/komplexni-validator#161]
Dobrý den,
rád bych se zeptal, kdy se předpokládá, že bude nová verze validátoru, která bude validovat oproti nejnovějším standardům?

Děkuji

**Comment by jbil7** [comment]
Dobrý den, minulý týden byla vydána nová verze validátoru (v. 2.4). Zatím se však jedná o betaverzi, která není určena k ostrému provozu, nýbrž pouze k testování a dolaďování. Až bude k dispozici ostrá verze, ozveme se Vám.

**Comment by FilipPavcik** [comment]
Issue zatváram, keďže nová verze 2.4.1 už bola vydaná.
