### ISSUE TITLE
Validátor 2.4-beta: Validátor nepovoluje hodnotu "user defined" u obrazových dat

### ISSUE THREAD

**Issue by FilipPavcik** [NLCR/komplexni-validator#164]
Staršie verzie Jpylyzeru v elementu `<precincts>` generovali hodnotu "yes". V najnovšej verzii Jpylyzer 2.2 je ale pridaná nová hodnota "**user defined**". Túto hodnotu potom validátor vyhodnotí ako chybu.

_mc_df53c210-d3f7-11e6-a1de-001018b3eb4c_0001.jp2: Precincts (regiony): hodnota "user defined" neodpovídá žádnému z omezení: [musí být přesně 'Yes',musí být přesně 'yes']_

Keďže konkrétnu hodnotu u obrazu DMF nepredpisuje, tak táto hodnota **"user defined"** by mala byť vo validátore tolerovaná. 
Nižšie posielam aj metadata, ktoré generuje staršia verzie Jpylyzeru a potom tá najnovšia:

Jpylyzer (1.18.0)
![image](https://github.com/NLCR/komplexni-validator/assets/86611996/458604d1-cb48-4cf2-a4bb-b284577828ef)

Jpylyzer (2.2.0)
![image](https://github.com/NLCR/komplexni-validator/assets/86611996/f882838a-28cd-48c4-8928-c366afca4472)

**Comment by rzeh4n** [comment]
V 69ccad42de9b4e6a609a0245df40247a904fd73e jsem doplnil hodnotu "user defined". 
Obecně DMF neuvádí očekávanou podobu výstupu Jpylyzer (apod.) pro obrázky UC a MC. Nejsem si jistý, jestli to řeší nějaký další odkazovaný dokument. 
Bylo to v původním zadání Validátoru: Obrázky musí splňovat, že jpylyzer bude mít v precincts tyhle povolené hodnoty, apod.

**Comment by jbil7** [comment]
Potvrzuji, že hodnota `user defined` byla do validatorConfig ve verzi 2.4.1 přidána do všech souborů jpylyzer.xml. Odzkoušeno v CLI v linuxu, velmi pravděpodobně však bude fungovat i jinde.

Issue uzavírám jako vyřešené.
