### ISSUE TITLE
Validátor verze 2.2.1 - ERROR u Supplement, element originInfo

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/komplexni-validator#167]
Dobrý den,
narazil jsem na tuto chybu ve validátoru 2.2.1. Možná se objevuje i v novější verzi.
U Supplementu validator vyžaduje element originInfo, který má ale příznak jen MA a má se vyplňovat, pokud se liší od údajů v popisu svazku monografie (stejný údaj ve standardech pro mono verze 1.8, 2.0, 2.1).

Chápu to dobře, že pokud má příloha stejné vydavatelské údaje, tak u ní element originInfo vyplňovat nemusí? Chybové hlášení pak lze ignorovat?

Děkuji

**Comment by fremrovaK** [comment]
Dobrý den,

děkujeme za upozornění. Jak píšete: pokud se vydavatelské údaje přílohy a svazku shodují, není dle DMF nutné `<originInfo>` vyplňovat. Na chybovou hlášku v tom případě neberte ohled.

**Comment by jbil7** [comment]
@Drahotussky Prosím, mohl bych Vás požádat o balíček a výpis z validátoru (+ verze validátoru, o kterou se jedná) ?

Pokouším se totiž replikovat problém a nedaří se mi to. Kromě toho jsem se díval do validačních profilů současné verze 2.4.1 i historické verze validátoru 2.2.1 a na úrovni přílohy jsem vždy viděl, že `originInfo` má nastaveno `mandatory=false`, tedy nepovinný údaj.

Děkuji.

**Comment by Drahotussky** [comment]
Vystupy z validatoru. Odkaz na balicek prijde mailem.
[2024_05_31_13_19_25_osa001-00134e-val. 2.2.1.txt](https://github.com/user-attachments/files/15512866/2024_05_31_13_19_25_osa001-00134e-val.2.2.1.txt)
[2024_05_31_13_26_32_osa001-00134e-val. 2.4.1.txt](https://github.com/user-attachments/files/15512867/2024_05_31_13_26_32_osa001-00134e-val.2.4.1.txt)

**Comment by jbil7** [comment]
Děkuji Vám za logy. Balíčky mi zatím nedorazily, ale to nevadí. Příčinu už nejspíše vidím a i se mi ji podařilo replikovat.

Kromě hlášené chyby je z logu taky patrné, že na úrovni SUPPL se ve Vašem balíčku nachází neočekávaný element `mods:recordInfo`, jehož dceřiným elementem je dle mého odhadu `<mods:descriptionStandard>rda</mods:descriptionStandard>`.

Výskyt neočekávaného elementu `recordInfo` je v pořádku, nicméně na základě něj se úroveň přílohy validuje dle validačního profilu pro RDA, v němž se nesprávně nachází pravidlo vynucující aspoň jeden element `mods:originInfo[@eventType='publication' or @eventType='production']` To je nastaveno v rozporu s papírovým DMF od v. 1.2 až do v. 2.1, kde se uvádí:

> plnit pokud se liší od údajů v popisu svazku monografie (platí i pro jednotlivé subelementy)

Jedná se tedy vskutku nikoli o chybu ve Vašem balíčku, nýbrž o chybu ve validátoru, kterou opravím.

**Comment by Drahotussky** [comment]
Dobrý večer,
neskončil odkaz na balíček ve spamu?

S pozdravem

Aleš Drahotussky

Dne so 1. 6. 2024 18:26 uživatel Jan Bilwachs ***@***.***>
napsal:

**Comment by jbil7** [comment]
Problém se týkal i periodik v. 1.7 - 2.0. Taktéž opraveno.

**Comment by jbil7** [comment]
Uzavírám jako opravené.
