### ISSUE TITLE
Validator 2.4 BETA - Jpylyzer nenalezen

### ISSUE THREAD

**Issue by FoxKyong** [NLCR/komplexni-validator#168]
Zkouším validátor verze 2.4 BETA a nenachází mi to Jpylyzer. Podle nápovědy je cesta dobře a samostatně Jpylyzer funguje. Zároveň by to teoreticky nemělo hlásit, že nebyl nalezen MP3val, shntool a Checkmate, když jsem je vůbec nespecifikoval? Syntaxe moje tady:

java -jar /data/KomplexniValidatorCLI-2.4-beta/KomplexniValidatorCLI-2.4-beta.jar --action VALIDATE_PSP --config-dir /data/KomplexniValidatorCLI-2.4-beta/validatorConfig --forced-dmf-per-version 1.8 --jhove-path /data/jhove/ --jpylyzer-path /data/jpylyzer/ -psp vkol-00a10u

Platforma: Linux; 64b
Kořenový adresář konfigurace validátoru: /data/KomplexniValidatorCLI-2.4-beta/validatorConfig
Kontroluji dostupnost nástroje ImageMagick: nalezen, verze: ImageMagick 6.9.11-60
Kontroluji dostupnost nástroje JHOVE: nalezen, verze: Rel. 1.20.1
Kontroluji dostupnost nástroje Jpylyzer: nenalezen (Cannot run program "jpylyzer": error=2, No such file or directory)
Kontroluji dostupnost nástroje Kakadu: nalezen, verze: v7.8
Kontroluji dostupnost nástroje MP3val: nenalezen (Cannot run program "mp3val": error=2, No such file or directory)
Kontroluji dostupnost nástroje shntool: nenalezen (Cannot run program "shntool": error=2, No such file or directory)
Kontroluji dostupnost nástroje Checkmate: nenalezen (Cannot run program "mpck": error=2, No such file or directory)
Zpracovávám PSP balík /data/backup/radim/test/vkol-00a10u
Bude použita verze standardu Periodika 1.8

**Comment by jbil7** [comment]
Prosím, s jakou verzí jpylyzeru jste to zkoušel? Pokusil jsem se replikovat Váš problém a příkazový řádek validátoru 2.4 beta mi s jpylyzerem funguje.

Od verze validátoru 2.4 je podporován pouze jpylyzer v 2.2. Taktéž u jhove je garantována kompatibilita pouze s v. 1.28 a vyšší. Viz https://github.com/NLCR/komplexni-validator/wiki/Instalace#jpylyzer

**Comment by jbil7** [comment]
@FoxKyong jpylyzer v. 2.2 funguje s pojednávanou v. 2.4-beta i s aktuální verzí Komplexního validátoru. Issue z toho důvodu uzavírám.
