### ISSUE TITLE
Jpylyzer - Valid: kontrolovaná hodnota nenalezena

### ISSUE THREAD

**Issue by kerschfilip** [NLCR/komplexni-validator#170]
Dobrý den,

Při kontrole obrazových dat mi validátor ve verzi 2.4 vrací chybu při kontrole mastercopy a usercopy pomocí Jpylyzer. Chyba je: `mc_aba007-000lam_0001.jp2: Valid: kontrolovaná hodnota nenalezena`. Objevuje se u všech obrazových souborů.

Jaká hodnota prosím v takovém případě není nalezena? Při kontrole souborů mimo validátor pomocí Jpylyzer se vše zdá OK. Výstup dokonce obsahuje řádek 
```xml
<isValid format="jp2">True</isValid>
```

Děkuji!

**Comment by FilipPavcik** [comment]
Dobrý deň,
ano, je to chyba validátoru. Podľa všetkého validátor očakáva hodnotu `"Valid"` a hodnotu `"True"` vyhodnotí ako chybu. 
Malo by sa to ale opraviť vo validátore.

**Comment by jbil7** [comment]
Chyba souvisí se změnou názvosloví ve výstupu jpylyzeru (počínaje jeho v. 2.0.0). Původně byl název elementu `isValidJP2`, nově se jedná o `isValid`.

Více viz https://jpylyzer.openpreservation.org/2019/11/20/Release-of-jpylyzer-2-0-0

Oprava bude provedena ve všech validačních profilech Komplexního validátoru pro MC a UC.

**Comment by jbil7** [comment]
Uzavírám jako opravené.
