### ISSUE TITLE
Jhove 1.29

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/komplexni-validator#171]
Dobrý den,
na wiki-Instalace se píše, že minimální podporovaná verze JHOVE je verze 1.29. Tu se mi ale nedaří nikde nalézt. Na GitHubu k JHOVE jsem narazil jen na verzi 1.28 a pre-release verzi 1.30.
Děkuji

**Comment by jbil7** [comment]
Testoval jsem v CLI verzi KV 2.4.1, že JHOVE 1.28 funguje. Patrně se tedy jedná o překlep v dokumentaci.

@rzeh4n Prosím, mohl byste potvrdit, že se jedná o překlep?

**Comment by rzeh4n** [comment]
Ano, je to verze 1.28. Doplním na https://github.com/NLCR/komplexni-validator/wiki/Instalace
