### ISSUE TITLE
Chybné určení kódování OCR ve validátoru verze 2.4.1 - viz issue 151

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/komplexni-validator#172]
Dobrý den,
při validaci ve validátoru 2.4.1 stále dochází k hlašení ERROR při validaci kodování UTF-8 u OCR
viz https://github.com/NLCR/komplexni-validator/issues/151
Chybové hlášení máme tedy nadále ignorovat?

Děkuji

**Comment by FilipPavcik** [comment]
Issue uzatváram ako duplicitné a poprosím vás sledovať pôvodné issue [https://github.com/NLCR/komplexni-validator/issues/151](https://github.com/NLCR/komplexni-validator/issues/151)
