### ISSUE TITLE
ImageMagick - ERROR: RegistryKeyLookupFailed_no decode delegate for this image format 

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/komplexni-validator#174]
Dobrý den,
při validaci obrázků se nám objevila tato chyba u programu Program ImageMagick ve verzi 7.1.1-29 (v příkazovém řádku se zobrazuje 7.1.1-Q16-HDRI)
ERROR: mc_osa001-00134e_0001.jp2: no_errors: zakázaná hodnota nalezena: identify: RegistryKeyLookupFailed `CoderModulesPath' @ error/module.c/GetMagickModulePath/668.
	ERROR: mc_osa001-00134e_0001.jp2: no_errors: zakázaná hodnota nalezena: identify: no decode delegate for this image format `JP2' @ error/constitute.c/ReadImage/746.

Ve verzi 7.0.7-3 se chyba neukázala.
Nemáme používat verzi 7.1.1-29?

Děkuji

**Comment by jbil7** [comment]
@Drahotussky Prosím, mohl byste poskytnout MC soubor, na kterém se projevila tato chyba? Děkuji.

**Comment by Drahotussky** [comment]
Řešili jsme to s firmou a pravděpodobně vyřešili. Šlo o to, že v počítači jsme neměli nainstalovanou verzi ImageMagick, která je v našem metadatovém editoru. Bylo nam receno, ze jsme nemeli na pc nejspis nastavene vsechny potrebne promenne v sys_path. Aplikace se snažila použít něco, co nejde.
Přesto posilam přes uschovnu obrázek
https://www.uschovna.cz/zasilka/PGYW4JFB9S7SZDXH-2I7/D72GHJMTJP

**Comment by jbil7** [comment]
Pokud se Vám podařilo problém vyřešit, pak bych issue zde uzavřel.
