### ISSUE TITLE
Chyba při validaci kapitoly monografie (standardy 1.4) -The content of element 'mods:detail' is not complete

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/komplexni-validator#178]
Dobrý den,
při validaci kapitoly monografie (standardy 1.4) na vyskočila tato chyba:
 ERROR: mets_e7547171-e143-4a24-8beb-92cc2d9b0a8f.xml: záznam MODSMD_CHAP_0001 není validní podle  mods_3.6.xsd: cvc-complex-type.2.4.b: The content of element 'mods:detail' is not complete. One of '{"http://www.loc.gov/mods/v3":number, "http://www.loc.gov/mods/v3":caption, "http://www.loc.gov/mods/v3":title}' is expected.

Takto vypadá zápis kapitoly:
<mets:dmdSec ID="MODSMD_CHAP_0001">
    <mets:mdWrap MDTYPE="MODS" MDTYPEVERSION="3.6" MIMETYPE="text/xml">
      <mets:xmlData>
        <mods:mods ID="MODS_CHAP_0001">
          <mods:language>
            <mods:languageTerm authority="iso639-2b" type="code">cze</mods:languageTerm>
          </mods:language>
          <mods:titleInfo>
            <mods:title>Už nikdy válku</mods:title>
          </mods:titleInfo>
          <mods:genre type="unspecified">chapter</mods:genre>
          <mods:part>
            <mods:detail type="pageNumber">
            </mods:detail>
            <mods:extent>
              <mods:start>[3]</mods:start>
              <mods:end>[4]</mods:end>
            </mods:extent>
          </mods:part>
          <mods:recordInfo>
            <mods:recordCreationDate encoding="iso8601">2024-04-04T09:14</mods:recordCreationDate>
          </mods:recordInfo>
          <mods:identifier type="uuid">baba8789-6a2f-4965-bc57-fe6c02ae5bca</mods:identifier>
        </mods:mods>
      </mets:xmlData>
    </mets:mdWrap>
  </mets:dmdSec>

Přikladam i mets dane knihy

V čem je problém? Děkuji

[mets_e7547171-e143-4a24-8beb-92cc2d9b0a8f_1.txt](https://github.com/user-attachments/files/15577780/mets_e7547171-e143-4a24-8beb-92cc2d9b0a8f_1.txt)

**Comment by jbil7** [comment]
@Drahotussky Dobrý den, jedná se o rozpor mezi DMF a XML schématem pro standard MODS, který se vyskytoval v DMF verzích 1.4 pro monografie a níže a také ve verzích 1.8 pro periodika a níže. Z pohledu XSD nesmí element `mods:detail` zůstat prázdný - to je příčinou problému. DMF však v elementu `mods:detail` předepisuje pouze atribut `@type` a žádný dceřiný element. V novějších DMF je tento rozpor již opraven. Viz také zde: https://github.com/NLCR/Standard_NDK/issues/117#issuecomment-582314027

Chybu tudíž můžete ignorovat.

Jelikož se nejedná o chybu ve validátoru, issue uzavírám jako wontfix.
