### ISSUE TITLE
Kontrola urn:nbn: chyba připojení při zpracování identifikátoru.

### ISSUE THREAD

**Issue by pepinovimr** [NLCR/komplexni-validator#184]
Dobrý den, v posledních dnech se nám na verzi 2.4.2 začalo stávat, že validátor hlásí:
`chyba připojení při zpracování identifikátoru [hodnota urn:nbn]: Read timed out.`
V resolveru ale dané urn:nbn normálně je a při opakované validaci již daný Error nevidíme.

Napadá mne, jestli nemůže být důvodem to, že samotná validace je nad hodně balíky (přes 50 issues) a s relativně velkým počtem mc/uc (přes 800 od každého),  u kterých se také validují obrazová data. Takže celá validace trvá přes hodinu a čtvrt.

Předem děkuji za odpověď. 
Josef Vimr

**Comment by jbil7** [comment]
Dobrý den,

Komplexní validátor u každého balíčku ověřuje dle resolveru NK běžícího na adrese `resolver.nkp.cz`, zda je urn:nbn platné. Tuto chybu validátor ohlásí, když se na resolver NK nemůže dostat. Vámi hlášenou chybu se mi podařilo zreplikovat tak, že jsem odpojil PC od internetu, pustil jsem validaci balíčku a dostal jsem se k podobné hlášce. Problém by tedy pravděpodobně mohl být síťový.

Prosím, zkusil byste ověřit, zda se ze systému, na němž validátor pouštíte, dostanete na API resolveru? 

Pracujete-li v desktopovém operačním systému, zkuste prosím do webového prohlížeče zadat tuto adresu (hodnotu `urn:nbn:cz:abc123-123456` v url prosím nahraďte urn:nbn Vámi testovaného balíčku):
`https://resolver.nkp.cz/api/v5/resolver/urn:nbn:cz:abc123-123456?format=json`

Pracujete-li v příkazovém řádku linuxu, zkuste prosím zadat (opět nahraďte urn:nbn):

`wget -q -O - https://resolver.nkp.cz/api/v5/resolver/urn:nbn:cz:abc123-123456?format=json`

Měla by se Vám v obou případech objevit metadata záznamu v json formátu - přesně těch se dožaduje validátor při kontrole. Pokud se tak nestane, příčina bude velmi pravděpodobně v dostupnosti url. Buď měl resolver NK krátkodobý výpadek, nebo se síťový problém nachází někde na Vaší straně. 

Množství validovaných balíčků by nemělo hrát roli. Běžně validuji tisíce balíčků vč. velkých monografií, taková validace běží i několik dní a na tuto hlášku jsem v praxi snad ještě nikdy nenarazil.

**Comment by pepinovimr** [comment]
Dobrý den,
děkuji za rychlou odpověď. Na desktopu, kde se validují balíčky je API dostupné.
Každopádně pokud validátor opravdu nemá problém s takto velkými balíky, tak usuzuji že problém bude jinde (jak jste říkal, buď výpadek resolveru, nebo spíš internet), budeme to dále pozorovat...
Issue, zavírám s tím že to není problém na straně validátoru.
Děkuji.
