### ISSUE TITLE
Problém s detekcí verze ImageMagic

### ISSUE THREAD

**Issue by isenkyr** [NLCR/komplexni-validator#28]
obracím se na vás dotazem ohledně psp validátoru a jeho použití s nástrojem imageMagic. Pokud použiji řádkovou utilitu C:\KomplexniValidatorCLI-v1.3 s argumenty 

 -dt Periodical -dv 1.6 -conf "C:\KomplexniValidatorCLI-v1.3\validatorConfig" -pd "D:\ExportDevelop\aee001-0005e5" -x "C:\Users\isenkyr.ELSYST01\AppData\Local\Temp\tmp6910.tmp" --imageMagick-path "C:\Program Files\ImageMagick-7.0.5-Q16" --jhove-path "" --jpylyzer-path "C:\jpylyzer" --kakadu-path "C:\Program Files (x86)\Kakadu"

tak dostanu výstup z validátoru 

Kontroluji dostupnost nástroje ImageMagick: není definován způsob detekce verze

Pokud použiji stejné argumenty pro verzi 1.2 tak se toto hlášení nevyskytuje.

**Comment by rzeh4n** [comment]
Ten způsob kontroly verze ImageMagick je definován v souboru validatorConfig/imageUtils.xml:
https://github.com/NLCR/komplexni-validator/blob/master/sharedModule/src/main/resources/nkp/pspValidator/shared/validatorConfig/imageUtils.xml#L65
Čili 
```
C:\Program Files\ImageMagick-7.0.5-Q16\magick.exe convert -version 
```
by mělo na standardní výstup vypsat něco, co odpovídá regulérnímu výrazu 
```
ImageMagick [0-9\.\-]+.
```
Co vám to vypisuje?
Taky by mohlo jít o změnu v novější verzi ImageMagick - nemají úplně jasno v tom, co vypisovat na standardní a co na chybový výstup. Třeba ten samotný výstup identify je potřeba pro LINUX a WINDOWS brát z STDERR, ale pro macOS ze STDOUT, což moc nedává smysl. Alespoň se to tak chová pro verzi ImageMagick-7.0.3-Q16.

**Comment by isenkyr** [comment]
Spustil jsem příkaz podle vašeho popisu a dostal jsem následující výpis na konzolu

Version: ImageMagick 7.0.5-1 Q16 x64 2017-03-04 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Visual C++: 180040629
Features: Cipher DPC Modules OpenMP
Delegates (built-in): bzlib cairo flif freetype jng jp2 jpeg lcms lqr openexr pangocairo png ps rsvg tiff webp xml zlib

**Comment by rzeh4n** [comment]
Tady bych taky poprosil ještě přesměrovat standardní a chybový výstup do vlastních souborů a vypsat je odděleně, tedy
```
C:\Program Files\ImageMagick-7.0.5-Q16\magick.exe convert -version 2>detection-err.txt 1>detection-out.txt
```
A doplnit zde obsahy souborů detection-err.txt a detection-out.txt

**Comment by isenkyr** [comment]
[detection-out.txt](https://github.com/NLCR/komplexni-validator/files/843896/detection-out.txt)

**Comment by FoxKyong** [comment]
Verzí ImageMagick to asi není. Právě jsem zkoušel použít 7.0.5-Q16 a validátor ji najde.

**Comment by isenkyr** [comment]
Už jsem na to přišel problém byl u mě. Měl jsem poškozený soubor imageUtils.xml. Stáhl jsem si novou verzi a už s nástrojem ImageMagic problém není.
