### ISSUE TITLE
Problém s nástrojem jpylyzer

### ISSUE THREAD

**Issue by isenkyr** [NLCR/komplexni-validator#29]
Pokud s příkazové řádky spustím nástroj jpylyzer

c:\jpylyzer>jpylyzer.exe "\\nas02.ee.cz\store\Export Testovaci\aee001-0005e5\mastercopy\mc_aee001-0005e5_0001.jp2"

tak se příkaz korektně provede.

Pokud spustím validaci KomplexnímValidátorem 1.3 nad balíkem na cestě 

\\nas02.ee.cz\store\Export Testovaci\aee001-0005e5

tak dostanu výpis z nástroje jpylyzer

checkImageFilesValidByExternalUtil: chyba parsování xml (výstup nástroje JPYLYZER): Premature end of file. (soubor \\nas02.ee.cz\store\Export Testovaci\aee001-0005e5\mastercopy\mc_aee001-0005e5_0001.jp2)

**Comment by rzeh4n** [comment]
Podle cesty jde o Windows, jaká verze?
Spouštíte to přes GUI, nebo CLI? Pokud CLI, tak prosím uveďte, s jakými přesně parametry to spouštíte. 
Vypadá to, že problém je v té relativní cestě, která při spuštění jpylyzer validátorem ukazuje na neexistující soubor.

**Comment by isenkyr** [comment]
Můj OS je Windows. Chyba se projevuje jak v GUI tak CLI verzi. Se síťovou cestou to asi souviset nebude teď jsem testoval na cestě D:\Export testovaci\aee001-0005e5 a chyba se projevila úplně stejně.

CLI spouštím s parametry
 -dt Periodical -dv 1.6 -conf "D:\VisualStudio\Programs\SiriusMETS\Tools\GeneralValidatorNdkForm\bin\Debug\Tools\KV_CLI-v1.3\validatorConfig" -pd "D:\Export testovaci\aee001-0005e5" -x "C:\Users\isenkyr.ELSYST01\AppData\Local\Temp\tmp9D3E.tmp" --imageMagick-path "" --jhove-path "" --jpylyzer-path "C:\Program Files (x86)\Jpylyzer\jpylyzer_1.17.0_win64(1)" --kakadu-path ""

Verze jpylyzer 1.17.0

**Comment by rzeh4n** [comment]
Nedaří se mi problém replikovat. Mohl byste to ještě spustit následovně?
```
c:\jpylyzer>jpylyzer.exe "\nas02.ee.cz\store\Export Testovaci\aee001-0005e5\mastercopy\mc_aee001-0005e5_0001.jp2" 2>execution-err.txt 1>execution-out.txt
```
Ale v PowerShellu, ne v cmd.exe (ten myslím neumí pracovat s přesměrování výstupních proudů).
Co obsahují soubory execution-err.txt a execution-out.txt?

**Comment by isenkyr** [comment]
Posílám výstup z jpylyzer spušteném v power shellu, pro error byl soubor prázdný. Ještě poznámku takhle to projde korektně, ale problém je když se to spustí přes validátor viz hned první příspěvek v issue.

[execution-out.txt](https://github.com/NLCR/komplexni-validator/files/843883/execution-out.txt)

**Comment by rzeh4n** [comment]
Vim, ze to takhle projde korektne, ale zajima me podrobne, jak se ta konkretni instalace Jpylyzeru chova i mimo validator, abych mohl identifikovat problem. Jeste by me tedy zajimal ten obsah execution-err.txt. 

Doufal jsem, ze treba tahle verze jpylyzeru zapisuje data pro zmenu tam, ale evidentne ne. Mohla by tam byt nejaka chybova hlaska jpylyzeru, protoze on podle vseho vraci prazdny soubor a ja netusim, proc. 

Pokud ani to ne, jeste by mohl byt teoreticky problem s vlakny, proto by me zajimala ta verze Windows a architektura (32/64 bit?). Protoze se tam deje to, ze spusteni nastroje, jako je jpylyzer, obsluhuji tri vlakna - jedno provadi samotne spusteni nastroje, druhe cte a uklada do promenne standardni vystup, treti zase chybovy vystup. Coz by mohl byt potencialni zdroj chyby.

**Comment by isenkyr** [comment]
Soubor execution-err.txt byl nulový. Můj OS je Windows10, 64bit.

**Comment by rzeh4n** [comment]
Nedaří se replikovat, zavírám.
