### ISSUE TITLE
Problém s diakritikou v cestě na soubor

### ISSUE THREAD

**Issue by isenkyr** [NLCR/komplexni-validator#30]
Nástroj jpylyzer nejde použít pro validaci psp balíku, který v cestě obsahuje diakritiku
Nástroj jhove nejde použít pro validaci psp balíku, který v cestě obsahuje mezery a diakritiku. Pokud se jhove použije validátor vrací nesmyslné hlášení např.

Error: checkImageFilesValidByExternalUtil: Last modified: kontrolovaná hodnota nenalezena (soubor D:\ExportDevelop\test test\aee001-0005e5\mastercopy\mc_aee001-0005e5_0001.jp2)
Error: checkImageFilesValidByExternalUtil: Size: kontrolovaná hodnota nenalezena (soubor D:\ExportDevelop\test test\aee001-0005e5\mastercopy\mc_aee001-0005e5_0001.jp2)

**Comment by rzeh4n** [comment]
```
PS C:\Users\Lenovo\Documents\software\jpylyzer_1.17.0_win64> .\jpylyzer.exe jp2In 'C:\tmp\Priserne zlutoucky kun\b50eb6b0-f0a4-11e3-b72e-005056827e52\usercopy\uc_b50eb6b0-f0a4-11e3-b72e-005056827e52_0001.jp2'
```
Výstup OK.
```
PS C:\Users\Lenovo\Documents\software\jpylyzer_1.17.0_win64> .\jpylyzer.exe jp2In 'C:\tmp\Příšerně žluťoučký kůň\b50eb6b0-f0a4-11e3-b72e-005056827e52\usercopy\uc_b50eb6b0-f0a4-11e3-b72e-005056827e52_0001.jp2'
User warning: jp2In does not exist
Traceback (most recent call last):
  File "<string>", line 729, in <module>
  File "<string>", line 725, in main
  File "<string>", line 626, in checkFiles
  File "<string>", line 500, in findFiles
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf8 in position 8: invalid start byte
```
Chyba
Takže ano, jpylyzer zvládá mezery, ale ne diakritiku v adresářích po cestě, alespoň tedy pro Windows. Což je problém jpylyzeru (snad i Windows kvůli jejich nepoužívání Unicode), ale ne Komplexního Validátoru.

```
PS C:\Users\Lenovo\Documents\software\jhove> .\jhove.bat -h XML -m jpeg2000-hul -k 'C:\tmp\Priserne zlutoucky kun\b50eb6b0-f0a4-11e3-b72e-005056827e52\usercopy\uc_b50eb6b0-f0a4-11e3-b72e-005056827e52_0001.jp2'
zlutoucky was unexpected at this time.
```
Chyba

```
PS C:\Users\Lenovo\Documents\software\jhove> .\jhove.bat -h XML -m jpeg2000-hul -k 'C:\tmp\Příšerně_žluťoučký_kůň\b50eb6b0-f0a4-11e3-b72e-005056827e52\usercopy\uc_b50eb6b0-f0a4-11e3-b72e-005056827e52_0001.jp2'
```
Výstup OK.
Takže jhove má zase problém s mezerami v názvech adresářů, diakritiku ale snese. Opět to není problém Komplexního Validátoru.

Jedině bych snad mohl upravit chybové hlášky, ale musí to být zase nějak obecně pro různé nástroje pro validaci obrazových dat, podobně jako při zjišťování verze, nebo spouštění nástroje a parsování výstupu.
