### ISSUE TITLE
Validátor CLI 1.3 a nástroj imageMagick

### ISSUE THREAD

**Issue by isenkyr** [NLCR/komplexni-validator#33]
Pokud jsou v cestě na psp balík mezery D:\Export testovaci\aee001-0005e5 tak má nástroj ImageMagick vyhazuje chybu checkImageFilesValidByExternalUtil: no_errors: zakázaná hodnota nalezena: identify: unable to open image 'D:\Export': Permission denied @ error/blob.c/OpenBlob/3094. (soubor D:\Export testovaci\aee001-0005e5\mastercopy\mc_aee001-0005e5_0001.jp2)

**Comment by rzeh4n** [comment]
Samotny ImageMagick mezery zvlada, pokud dostane parametr s mezerami takto v uvozovkach:
```
magick.exe identify -verbose 'C:\tmp\Priserne zlutoucky kun\b50eb6b0-f0a4-11e3-b72e-005056827e52\usercopy\uc_b50eb6b0-f0a4-11e3-b72e-005056827e52_0001.jp2'
```
Tohle je chyba validatoru a muze se tykat i jinych nastroju, nez ImageMagick.
Opraveno v 939be3f5c1699324d69b1f19beab87b6ae2c83cb, od verze 1.4 by to melo byt fungovat.
