### ISSUE TITLE
Komplexní validator GUI java verze - nejde spustit na linuxu s openjdk

### ISSUE THREAD

**Issue by FoxKyong** [NLCR/komplexni-validator#35]
Na linuxu s openjdk nejde spustit KomplexniValidatorGUI.jar. Po spuštění se zobrazí chyba:
```
Error: Could not find or load main class nkp.pspValidator.gui.Main
```

**Comment by rzeh4n** [comment]
Mozna chybi javaFx pro OpenJdk?
apt-get install openjfx

**Comment by FoxKyong** [comment]
Jo, díky, to  bylo ono. Jenom teda, jestli by to mohlo být připsané k dokumentaci, že java GUI to vyžaduje? Ať pak někdo nemá stejný problém.
Jenom teď mám další problém, nejde mi vybrat nic z menu, když kliknu třeba na nastavení nebo validovat, tak se zobrazí ty nabídky a hned zase zmizí, vybrat teda nic nejde. Nevím, jestli to jde pochopit z popisu, jak bude více času, tak natočím video, jak se to chová.

**Comment by rzeh4n** [comment]
Dopleno do wiki, dalsi problem prosim do noveho issue.

**Comment by FoxKyong** [comment]
V dokumentaci by mělo být uvedeno pouze, že je potřeba openjfx, případně uvedeno, že apt-get je pouze u distribucí, které používají .deb balíčky a to nevím, jestli všechny distribuce tu verzi mají stejně pojmenovanou. Jak jsem psal v komentáři, na Arch Linuxu je instalace "pacman -S java-openjfx", takže je tam jiný postup instalace i jiný název. Není podle mě dobré to psát takhle, jako by se předpokládalo, že každý má pouze Debian/Ubuntu. U jiných software je většinou vždy postup instalace uveden pro různé typy distribucí, tak to podle mě nevypadá takhle dobře.
