### ISSUE TITLE
Technická metadata - nenalezen očekávaný povinný element

### ISSUE THREAD

**Issue by volodymyrdn** [NLCR/komplexni-validator#37]
Komplexní validátor v1.5 zahlasil chybu při validování Texnických metadat: amd_mets_xxx.xml: 
_OBJ_002: /mets:techMD/mets:mdWrap/mets:xmlData/premis:object: nenalezen očekávaný povinný element 'premis:linkingEventIdentifier'._
 Element ale v *xml souboru existuje (https://github.com/NLCR/komplexni-validator/files/910035/amd_mets_cnb000103809_0001.xml.txt). Předchozí verze validátoru (1.4) při validování stejného psp balíčku tuto chybu nehlásí.

**Comment by godnat** [comment]
Dobrý den,

mezi verzemi 1.4 a 1.5 jsme měnili povinnosti u elementů pro část Premis. Pro archivační kopii (jp2) by toto nemělo být reportováno, pouze pro primární sken. Validátor jsme zřejmě chybně nastavili.
Můžete nasdílet balíček?

**Comment by volodymyrdn** [comment]
Dobrý den, 
přikládám testovaný psp balíček: 
[cnb000103809.zip](https://github.com/NLCR/komplexni-validator/files/910169/cnb000103809.zip)

**Comment by godnat** [comment]
Balíček je správně, element premis:linkingEventIdentifier je povinný jen u primárního skenu a ten tam máte. Validátor ho očekává i u archivního souboru (jp2) a to není podle specifikace, moje chyba, budeme řešit.

**Comment by volodymyrdn** [comment]
Dobrý den, a děkuji :)

**Comment by godnat** [comment]
Od verze 1.5.1 nebude validátor toto reportovat jako chybu.
