### ISSUE TITLE
structMap - hlásí neexistenci odkazu na existující soubor

### ISSUE THREAD

**Issue by mirek-khodl** [NLCR/komplexni-validator#38]
Validátor 1.5, OS Win64CZ, GUI verze

vypsaná  chyba - opakuje se pro všechny typy souborů (mc, uc, alto, txt):

amd_mets_abe045-00a4v6_0001.xml: fyzická strukturální mapa neobsahuje odkaz na soubor mc_abe045-00a4v6_0059  (vzal jsem namátkou soubor 0059):

Sekce v mapě přitom:
<mets:fptr FILEID="mc_abe045-00a4v6_0059" /> 
<mets:fptr FILEID="uc_abe045-00a4v6_0059" /> 
<mets:fptr FILEID="alto_abe045-00a4v6_0059" /> 
<mets:fptr FILEID="txt_abe045-00a4v6_0059" /> 

(PRIMARY_METS 3x OK)

**Comment by godnat** [comment]
Dobrý den,

můžete nasdílet balček? Vyzkoušíme.

**Comment by mirek-khodl** [comment]
Veřejně linkovat rozpracované PSP nemohu, to pouze vlastník.
Část odpovídající neobrazovým datům snad ano... Postačí?

**Comment by godnat** [comment]
Ano, to by mělo stačit.

**Comment by mirek-khodl** [comment]
Tedy zde: https://goo.gl/JFGJMk

**Comment by godnat** [comment]
Dobrý den,
validátor reaguje správně podle specifikace (DMF 1.2 s. 91), i když to z výpisu chyby není hned zřejmé. Podle specifikace má být ve fyzické mapě vedlejších mets záznamů pouze jeden element <div>, Vy máte dva elementy <div>-ten druhý tam validátor neočekává a uvedené soubory tak kvůli němu nemůže najít.

**Comment by mirek-khodl** [comment]
Děkuji za vysvětlení. Dovolím si ovšem upozornit, že formulace není jednoznačná jen proto, že ji takto jednoznačně interpretujete, což bylo asi prvotní příčinou vznesení dotazu.

Zápis mi dovoluje bez potíží interpretovat  informaci 7.6.2 <structMap> bude obsahovat pouze jeden <div> element s atributem TYPE="MONOGRAPH_PAGE" také takto:

Vynechme diskutabilní slovo "pouze", správně by bylo použito "právě jeden", ale i tak by se sdělení četlo takto: v právě jednom div elementu se musí vyskytnout atribut s typem MONOGRAPH_PAGE. Tady není ani slovo o tom, že nemůžete použít jiné divy s jinými atributy. Informace o jediném výskytu se vztahuje k popisu obsahu divu jako celku, nebo tak může být vnímána. Odpor k výskytu jakéhokoli jiného, z Vašeho pohledu nadbytečného, elementu div, nemá v takto specifikované podobě oporu. 

Nicméně to jsem popsal případ, který nenastal, neboť my se soustředíme na další úroveň vnoření (předchozí výklad se týkal souřadného vložení elemntu div s jinými atributy):  pokud do elementu shora vedeného jako div  vnořím do libovolné nižší úrovně zanoření elementy <fptr>, pak stále splňuji podmínku vnoření odkazu a vysvětlení, že validátor s něčím nepočítá, je věcně správné, argumentačně však nezakládá právo hovořit o chybě předloženého xml, formální stránka výkladu připouští ještě mnohem komplikovanější konstrukce. Zásadním nedostatkem DMF specifikace je samotný fakt, že ji nevytvořil specialista na výrokovou logiku (bez urážky kohokoli). Všichni bychom už několik let vytvářeli kompatibilní výstupy :). Uzavírám jako problém, kdy NDK balíček přijme, přesto bude validátor signalizovat všem projekťákům digitalizačních projektů, že jsou výstupy nevalidní. Paráda.
