### ISSUE TITLE
Validátor vyžaduje povinný dc:source, ten je podle DMF je nepovinný

### ISSUE THREAD

**Issue by volodymyrdn** [NLCR/komplexni-validator#40]
Dobrý den,

Při validování PSP balíčku Periodical 1.6, validátor (v1.5) zahlásil chybu:
**validační sekce:** Bibliografická metadata
**Pravidlo:** BIBLIOGRAPHIC_METADATA_MATCH_PROFILE_TITLE
**text chyby:** DCMD_TITLE_0001: /oai_dc:dc: nenalezen očekávaný povinný element 'dc:source'

Podle standardu, **dc:source** je povinný pouze pro tag **shelfLocator**, který je subelementem tagu **location**, který není povinný. Ve validovaném projektu tag **location** není. Mohli byste mi s tím poradit, kde je chyba? Děkuji.

V příloze přikládám mets soubor. [mets_zp022262-001_2017_0001.xml.txt](https://github.com/NLCR/komplexni-validator/files/941189/mets_zp022262-001_2017_0001.xml.txt)

**Comment by godnat** [comment]
Dobrý den,

chyba je u nás, element nemá být povinný, upravíme ve validátoru.

**Comment by godnat** [comment]
Nová verze 1.5.1 nebude reportovat absenci dc:source jako chybu. Souvisí s #31. Ideální stav je, že to bude časem reportováno jako WARNING. Proto enhancement

**Comment by rzeh4n** [comment]
Tady by to varování stejně nebylo moc užitečné, protože dc:source může obsahovat stejnou hodnotu, jako v MODSu:
 - location/url
 - location/physicalLocation
 - location/shelfLocator
