### ISSUE TITLE
Strukturální mapy - fyzická strukturální mapa neobsahuje element mets:div[@TYPE='Periodical']

### ISSUE THREAD

**Issue by volodymyrdn** [NLCR/komplexni-validator#41]
Dobrý den,

Při validování PSP balíčku Periodical 1.6, validátor (v1.5) zahlásil chybu:
**validační sekce:** Strukturální mapy
**Pravidlo:** PRIMARY-METS_PHYSICAL_STRUCTURAL_MAP_CORRECT
**text chyby:** mets_zp022262-001_2017_0001.xml: fyzická strukturální mapa neobsahuje element mets:div[@TYPE='Periodical']

Fyzická strukturální mapa obsahuje element mets:div[@TYPE='periodical'] (malé P), což je podle standardu:
![vystrizek](https://cloud.githubusercontent.com/assets/27212548/25220160/35340f18-25b1-11e7-8c47-e3fc4622376f.PNG)
Ale ve vzorových projektech, hodnota elementu type vždycky má velké první písmeno: Periodical.
Mohli byste poradit, která varianta je správná?
Děkuji.

**Comment by godnat** [comment]
Dobrý den,

obě varianty jsou aktuálně správné. Ze specifikace není zřejmé, zda "periodical" je jediný možný zápis a liší se též zápis v našem vzorovém balíčku, kde je "Periodical", proto upravíme validátor aby akceptoval oba zápisy.

Díky

**Comment by rzeh4n** [comment]
Od verze validátoru 1.7 se nebude kontrolovat (zakomenováno).
Vzhledem k tomu, že v DMF Periodika (i ve verzi 1.7) je stále "např. periodical", není co dále upravovat. Dokud nebude v DMF řečeno, že tam musí být konkrétní hodnota nebo některá z výčtu hodnot, může tam být cokoliv. Podobně pro monografie.

**Comment by PavlinaKocisova** [comment]
v DMF 1.8 bude hodnota opravena na "Periodical", v případě monografií 1.4 na "Monographic". Předchozí vyjádření p. Řehánka zůstává v platnosti.
