### ISSUE TITLE
nepovolená hodnota atributu PAGE TYPE

### ISSUE THREAD

**Issue by mirek-khodl** [NLCR/komplexni-validator#42]
Dd,

při validaci typů stran dostáváme warning. Je důsledkem faktu, že nedošlo včas ke sjednocení popisu typů stran v primárním metsu - fyzikální str. mapě:  ...záznam stránky PAGE_#### ve fyzické strukturální mapě: nepovolená hodnota atributu TYPE ('backEndpaper')

Na základě [https://github.com/ceskaexpedice/kramerius/issues/297] byly přidány tvůrci Krameria dle požadavku knihovníků do množiny popisných údajů i typy, které nebyly ve výsledku přidány do později editovaného odkazu na pravidla paginace [http://goo.gl/z5NA0Q]

Mezitím jsme ovšem začali některé typy používat pro zakázky klientů a rozsahy doprogramovali do svého MDE, předpokládám, že tak učinili i původní žadatelé o rozšíření. Např. backEndpaper - Zadní předsádka, Errata, apod. (Narozdíl od ořízky poměrně smysluplné popisky ;) )

Nejde o velký problém a kdyby zůstaly výčtové typy pouhým řetězcovým literálem s typovou validací, byl by klid...,  nicméně určitou vadu spatřuji v neschopnosti sjednotit požadavky zpřístupnění (Kramerius, odkud hist. vychází zdroje pro popis paginace) a LTP (NK), přitom jsou poměrně těsně "konstrukčně" programově svázány. Použitá rozšíření nekolidují s jinými možnými typy více než ostatní typy stran. Úkol je to ale více pro NK než pro autory validátoru, kteří maximálně přizpůsobí validační šablony.

**Comment by Drahotussky** [comment]
Stejný problém je i s typem stránky Index (rejstřík)

**Comment by rzeh4n** [comment]
Opraveno v 10d6e62e0f3266016623400d9cfb16761d2e2a96 - doplnil jsem všechny typy z aktuální verze https://docs.google.com/document/d/1NrMnE7IOXO_v68ISh25wosColW6YafUDvYZ_hLg6cVo/edit#heading=h.8adx1xef1uwu. Čistě formálně by tam měly být hodnoty z verze z roku 2012, protože na to se odkazuje DMF. Jenomže podle hlavičky byly ty verze v roce 2012 dvě a není úplně zřejmé, co se konkrétně změnilo a prostě je to nesmysl už jenom kvůli zpětnému zavádění "Index" namísto "index" tímto postupem.
Souhlasím, že je v těch typech stran chaos. Měly by se definovat přímo v DMF a ne nějakým odkazem na vyvíjecí se dokument. Pokud příjde změna třeba ze strany Krameria, měla by se projevit v další verzi DMF a ne takto.
