### ISSUE TITLE
chyba v zápisu Xpath 'mods:namePart[@type=given']'

### ISSUE THREAD

**Issue by volodymyrdn** [NLCR/komplexni-validator#43]
Dobrý den, 

narazil jsem se na drobnou chybu během validaci vnitřní části balíčku: 

_chyba v zápisu Xpath 'mods:namePart[@type=given']': javax.xml.transform.TransformerException: misquoted literal... expected single quote!_

Chyba je v souboru **KomplexniValidatorGUI-v1.5\validatorConfig\fDMF\monograph_1.2\biblioProfiles\mods\internalpart_picture_aacr2.xml**

**Comment by godnat** [comment]
Děkujeme, opravíme v dalším releasu
