### ISSUE TITLE
Varování u identifikátorů

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/komplexni-validator#44]
Dobrý den,
v případě, že má kniha 2 cnb (jedno neplatné), hlásí validátor Varování, že seznam obsahuje více identifikátorů stejného typu. 

S pozdravem

A. Drahotušský

**Comment by ZdenekVasek** [comment]
Validátor reagoval správně. U daného balíku upozornil (varování) na více identifikátorů v DC - to je danost DC, který neumožňuje identifikovat neplatné identifikátory. Validátor proto dává upozornění pro zpracovatele, zda stav odpovídá záměru. Dále upozornil na vícenásobný výskyt čísla OCLC, které by mělo být unikátní (pro dlouhodobé uložení tato chyba nepředstavuje problém).
