### ISSUE TITLE
Bibliografická metadata - Přílohy

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/komplexni-validator#45]
U přílohy vyskakuje ERROR, že nebyl nalezen povinný element dc: creator. Podle standardů  povinný není.

S pozdravem

A. Drahotušský

**Comment by ZdenekVasek** [comment]
Dobrý den,
 
na úrovni supplement je u elementu <name> povinnost nastavena jako "mandatory," což znamená, že <dc:creator> je pro vyplňovaní povinný také - jedná se o základní top element. Validátor tuto chybu vyhodnotil správně v souladu se stávající specifikací.

**Comment by Drahotussky** [comment]
Dobrý den,
ve standardech vidím u monografie u elementu **name** příznak **MA**. 
Pokud by byl autor povinný a nemám možnost ho zjistit, jak máme element vyplnit?

Děkuji

**Comment by ZdenekVasek** [comment]
Povinnosti jsou hiearchické, tj. name je MA a pokud není přítomno, tak by měl validátor balíček pustit. Pokud je však použito name, tak namePart je již povinné. Vždy platí, že vnořené elementy jsou povinné v závislosti na stupni povinnosti nadřazených elementů.

**Comment by Drahotussky** [comment]
Vidím to stejně. My u přílohy právě element name použitý nemáme vůbec

**Comment by godnat** [comment]
U mono 1.2 upraveno, dc:creator je nepovinný (tj. absence není ani chyba ani varování), úprava je platná od další verze validátoru (tj. 1.6.1 nebo 1.7)
