### ISSUE TITLE
Kapitoly

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/komplexni-validator#46]
U jednoho balíčku nám vyskočila tato chybová hláška:
ERROR: MODSMD_CHAP_0001_0046: /mods:mods/@ID: hodnota 'MODS_CHAP_0001_0046' neodpovídá regulárním výrazu 'MODS_CHAP_[0-9]{4}'

Kapitoly jsou u všech knih tvořeny stejně, v samotném projektu nema zadna kapitola nazev MODS_CHAP_0001_0046¨

Děkujeme za pomoc

S pozdravem

A. Drahotušský

**Comment by ZdenekVasek** [comment]
Validátoru vadí struktura pojmenování. I specifikace předpokládá využití jen 4 čísel, tedy jen CHAP_0001, následná část s _0046 je navíc. Pro rozhodnutí, zda by daný způsob zápisu znamenal i problémy při uložení bychom potřebovali celý balíček.

**Comment by Drahotussky** [comment]
Dobry den,
zjistil jsem,ze chybove hlaseni se tyka pojmenovani vnitrni casti vytvorene v ramci prilohy knihy. 
Cislice 0001 je oznacenim svzaku monografie, 0046  je pak cislem vnitrni casti v priloze

<mets:dmdSec ID="MODSMD_CHAP_0001_0046">
    <mets:mdWrap MDTYPE="MODS" MDTYPEVERSION="3.4" MIMETYPE="text/xml">
      <mets:xmlData>
        <mods:mods ID="MODS_CHAP_0001_0046">
          <mods:language>
            <mods:languageTerm authority="iso639-2b" type="code">ger</mods:languageTerm>
          </mods:language>
          <mods:titleInfo>
            <mods:title>Volkslieder. Der Zippelpelz</mods:title>
            <mods:partNumber>Nr. 171</mods:partNumber>
          </mods:titleInfo>
          <mods:genre type="chapter">CHAPTER</mods:genre>
          <mods:part>
            <mods:extent>
              <mods:start>24</mods:start>
              <mods:end>24</mods:end>
            </mods:extent>
          </mods:part>
          <mods:recordInfo>
            <mods:recordCreationDate encoding="iso8601">2017-05-11T08:36</mods:recordCreationDate>
          </mods:recordInfo>
          <mods:identifier type="uuid">eb216cbc-a76f-4e54-9bd8-9b32e0707441</mods:identifier>
        </mods:mods>
      </mets:xmlData>
    </mets:mdWrap>
  </mets:dmdSec>
  <mets:dmdSec ID="DCMD_CHAP_0001_0046">
    <mets:mdWrap MDTYPE="DC" MIMETYPE="text/xml">
      <mets:xmlData>
        <oai_dc:dc>
          <dc:title>Volkslieder. Der Zippelpelz</dc:title>
          <dc:description>Nr. 171</dc:description>
          <dc:type>model:internalpart</dc:type>
          <dc:coverage>24</dc:coverage>
          <dc:coverage>24</dc:coverage>
          <dc:identifier>uuid:eb216cbc-a76f-4e54-9bd8-9b32e0707441</dc:identifier>
          <dc:language>ger</dc:language>
        </oai_dc:dc>
      </mets:xmlData>
    </mets:mdWrap>
  </mets:dmdSec>

**Comment by rzeh4n** [comment]
DMF Monografie 1.2 v kapitole 7.3.1 na straně 22 mluví jasně:

> ID u elementu <mods>: Identifikátory budou začínat prefixy: MODS_TITLE, MODS_VOLUME,
MODS_SUPPL, MODS_CHAP, MODS_PICT pro MODS, obdobně pro DC. Za ty se dále přidá
podtržítko a číslo, identifikující pořadí identifikátoru, zarovnané a doplněné o nuly na 4 místa. Čtyřmístná
pořadová čísla u ID jsou uvedena proto, aby byla v celém dokumentu jednotná. ID tedy vypadá
následovně:

...

> kapitola (může být více)
• MODS_CHAP_XXXX, kde XXXX je pořadové číslo kapitoly, např. MODS_CHAP_0001 je
první kapitola atd.
• DC_CHAP_XXXX, kde XXXX je pořadové číslo kapitoly, např. DC_CHAP_0001 je první
kapitola atd.

Takže z pohledu Validátoru je to v pořádku.
