### ISSUE TITLE
namePart - atribut type

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/komplexni-validator#47]
U několika knih je hlášena ERROR:
ERROR: MODSMD_VOLUME_0001: /mods:mods/mods:name/mods:namePart[not(@type)]: nenalezen povinný atribut 'type'

V souboru METS, ale autor ma element **type** u příznaku **date**

-<name type="personal" usage="primary">

<namePart>Peter, Anton</namePart>

**<namePart type="date">1831-1898</namePart>**

-<role>

<roleTerm type="code" authority="marcrelator">com</roleTerm>

</role>

-<role>

<roleTerm type="code" authority="marcrelator">edt</roleTerm>

</role>

O jaký problém tady jde?

**Comment by ZdenekVasek** [comment]
Dobrý den, 
podle specifikace by mělo být autorovo jméno rozděleno do dvou elementů <namePart>, které jsou označené příslušným type atributem (pokud to není situace, kdy nelze rozlišit křestní jméno a příjmení). Vzhledem k tomu, že atributy "given" a "family" mají povinnost MA (což v tomto případu logicky možné je), validátor trvá na jejich použití. U "date" je atribut pouze doporučený, a validátorem může být hodnocen jako nedostačující. Date je v tomto smyslu určeno jen pokud je autorem akce (pokud by autorem byla např. konference bez konkrétního editora a pod.). Součástí namepart nemají být životní data autora.

**Comment by Drahotussky** [comment]
Dobrý den,
nám se z katalogizačního záznamu automaticky stáhne autor (jméno i příjmení, autor je tam v jednom poli) do elementu namePart a životopisné údaje do namePart s příznakem date. Je tedy třeba takový záznam opravit a jméno i příjmení dát do samostatných elementů namePart s příznaky (type) given a family?
Díval jsem se, že u jiných knih validátor nenahlásil žádný ERROR, i když byl autor zapsán v jednom elementu namePart. Je možné, že v těchto případech použil jen WARNING

Děkuji

**Comment by Drahotussky** [comment]
Dobrý den,
nám se z katalogizačního záznamu automaticky stáhne autor (jméno i příjmení, autor se tam dá zapsat jen v jednom poli) do elementu namePart a životopisné údaje do namePart s příznakem date. Je tedy třeba takový záznam opravit a jméno i příjmení dát do samostatných elementů namePart s příznaky (type) given a family

Díval jsem se, že u jiných knih validátor nenahlásil žádný ERROR, i když byl autor zapsán stejným způsobem. Je možné, že v těchto případech použil jen WARNING.
I u knih z NDK jsem našel autory zapsané stejným způsobem.

Píšete, že součástí namePart nemají být životopisná data, ale když vytvořím element name se všemi type, vypadá to takto:

<mods:name type="personal">
<mods:namePart type="family">Bergmann</mods:namePart>
<mods:namePart type="given">František</mods:namePart>
<mods:namePart type="date">1856-1942</mods:namePart>

Děkuji

**Comment by rzeh4n** [comment]
Jde o chybu v bibliografické šabloně a projevuje se jen u jednosvazkových monografií katalogizovaných podle RDA. Bylo kontrolováno, že pro element mods:namePart takový, který nemá atribut type, platí: element má atribut type. Což je logický nesmysl.
Opraveno v 1ff2d4503f315a69b7fd2e2408562910d43d0a69.
Ještě bych poupravil, že pro validátor jsou všechny příznaky povinnosti kromě M (MA, R, RA, O) považovány za nepovinné, protože validátor nemá jak kontrolovat jestli data jsou dostupná, to je informace pro výrobu záznamu, ne pro validaci. I když budoucna se uvažuje o informační hlášce pro některé z nich (zatím MA).
Platí tedy to, co se píše v DMF Monografie 1.2 na straně 28: Může být jak namePart bez atributu type, tak i s atributem type, přičemž jsou povoleny jen hodnoty date, family, given a termsOfAddress. Validátor dále kontroluje už jen to, že je alespoň jeden element namePart přítomen.
