### ISSUE TITLE
7.3.1.5 Mono - PICTURE

### ISSUE THREAD

**Issue by mirek-khodl** [NLCR/komplexni-validator#48]
Pustil jsem cvičně validátor na PSP s obrazovou vnitřní částí. V ukázkovém mono balíčku NDK jsem vzor na obrázky nebo kapitoly nenašel vůbec... IMHO by měl referenční balíček obsahovat VŠECHNY možnosti, které standard popisuje.

Nastavení pravidel validace v případě uvedení jména autora ve zkráceném tvaru (pro nedostatek zdrojových dat tedy použito např. pouze příjmení) na "M" dle mého názoru neodpovídá popisu na s. 54-55 verze 1.2

Část kódu:
```
<mods:name>
     <mods:namePart>Wladimirow, N.</mods:namePart>
       <mods:role>
           <mods:roleTerm type="code" authority="marcrelator">aut</mods:roleTerm>
       </mods:role>
  </mods:name>
```

Validátor: Error level:
 MODSMD_PICT_0015: /mods:mods/mods:name: nenalezen povinný atribut 'type'

Jako doplněk pak:
MODSMD_PICT_0015: chyba v zápisu Xpath 'mods:namePart[@type=given']': javax.xml.transform.TransformerException: misquoted literal... expected single quote!

namePart je MA a ve zjednodušeném zápisu se type nevyužívá
Pokud se celá sekce nevyplní, autor není znám, je validace OK

**Comment by Drahotussky** [comment]
Pokud je zapsán autor (viz výše) jako autor celého díla, dochází také k chybové hlášce?

Děkuji

MODSMD_PICT_0015: chyba v zápisu Xpath 'mods:namePart[@type=given']': javax.xml.transform.TransformerException: misquoted literal... expected single quote!

Na tento problém je tuším již upozornění v Issue 43

**Comment by ZdenekVasek** [comment]
Dobrý den, jde o chybu validátoru, bude opravena. Správný je váš výklad.

**Comment by godnat** [comment]
Upraveno zatím pro verze mono 1.2 a periodika 1.6, bude platit od verze validátoru 1.6.1 příp. 1.7

**Comment by godnat** [comment]
Upraveno pro všechny verze specifikací, úprava bude platit od další verze validátor (tj. 1.6.1 nebo 1.7)
