### ISSUE TITLE
Validátor CLI stále hlásí, že nástroj kakadu není dostupný

### ISSUE THREAD

**Issue by isenkyr** [NLCR/komplexni-validator#49]
Dobrý den,

pokud používám validátor 1.5 CLI tak vždy dostávám informativní hlášení, že Nástroj Kakadu není dostupný.
Přikládám obrázky s příkazovou řádkou a obsahem složky kakadu.
![kakadu](https://cloud.githubusercontent.com/assets/19608475/26340870/19639412-3f91-11e7-8c89-f7ea7e179797.png)

Příkazová řádka:
 -a VALIDATE_PSP -config-dir "D:\VisualStudio\Programs\SiriusMETS\Tools\GeneralValidatorNdkForm\bin\Debug\Tools\KV_CLI-v1.5\validatorConfig" -psp "D:\ExportDevelop\abe045-00a55y" -xml-protocol-file "C:\Users\isenkyr.ELSYST01\AppData\Local\Temp\tmp15D3.tmp" --force-dmf-per-version 1.6 Periodical --imageMagick-path "C:\Program Files\ImageMagick-7.0.5-Q16" --jhove-path "C:\Program Files (x86)\jhove" --jpylyzer-path "C:\Program Files (x86)\Jpylyzer\jpylyzer_1.17.0_win64(1)" --kakadu-path "C:\Program Files (x86)\Kakadu"

**Comment by FoxKyong** [comment]
Tak jsem to teď zkoušel na windowsu a píše mi to to stejné. Na linuxu to funguje normálně a kakadu to bere.

**Comment by godnat** [comment]
Verze 1.5 na windows 10 se Kakadu též nespustí. Verze 1.4 Kakadu na stejných Windows spustí. Budeme řešit.

**Comment by rzeh4n** [comment]
Bude opraveno ve verzi následující za 1.6, asi teda 1.7.

**Comment by rzeh4n** [comment]
Opraveno v commitech:
fd0c7f0a610fa82864fdb22da239115ee2198efa
706989306d65d9d4b744beb576e069ff84890115

**Comment by rzeh4n** [comment]
Dávno vyřešené.
