### ISSUE TITLE
Není možnost vybrat složku k validování

### ISSUE THREAD

**Issue by SykoraLukas** [NLCR/komplexni-validator#50]
Nainstaloval jsem GUI validátor pro Windows. Při spouštění KomplexniValidatorGUI.exe není možnost vybrat složku kterou chci validovat a rovněž chybí všechny tlačítka. 
<img width="701" alt="capture" src="https://user-images.githubusercontent.com/27210823/27732910-c8eacf3e-5d93-11e7-945b-2f413ce43e94.PNG">

Pokud však spustím KomplexniValidatorGUI.jar mohu vybrat složku a i tlačítka. 
<img width="961" alt="stlacitky" src="https://user-images.githubusercontent.com/27210823/27733104-9859c086-5d94-11e7-9f79-12a14bc8998c.PNG">

**Comment by godnat** [comment]
Verze 1.6 na Windows 10 spouštění přes KomplexniValidatorGUI.exe i přes KomplexniValidatorGUI.jar
umožňuje vybrat složku k validaci. 

Verze 1.5 na Windows 10 spouštění přes  KomplexniValidatorGUI.exe umožní též vybrat složku k validaci a i jiná tlačítka se zobrazují. 

Můžete vyzkoušet verzi 1.6? Případně popsat blíže prostředí kde aplikaci pouštíte.
