### ISSUE TITLE
eventType

### ISSUE THREAD

**Issue by ZdenekVasek** [NLCR/komplexni-validator#51]
Validátor vyhodnotil jako chybu záznam vzniklý z transformace nepublikovaného dokumentu, i když je vytvořen v souladu se specifikací.  
Výstup validace: 
Error: MODSMD_VOLUME_0001: /mods:mods: nenalezen očekávaný povinný element 'mods:originInfo[@eventType='publication']'
Je třeba, aby v souladu se specifikací (pro monografie verze 1.2, s. 31-32) připouštěl i možnost eventType:production.

**Comment by rzeh4n** [comment]
Podle mě se na straně 30 (v prvním odstavci u originInfo eventType) uvádí povinnost mods:originInfo[@eventType='publication']. přičemž třeba další originInfo s eventType production, distribution, manufacture nebo copyright jsou nepovinná.

Na druhou stranu v následujícím odstavci se mluví o minimálním MARC záznamu (který vyžaduje povinně buď 264_1 nebo 264_0:
```
Ve schválené interpretaci pro minimální záznam
pro textové monografické zdroje jsou povinným
údajem pouze údaje o nakladateli, tedy pole 264
s druhým indikátorem 1 a v případě
nepublikovaných disertací/rukopisů pole 264 s
druhým indikátorem 0 a podpolem $c.
Údaje o distribuci, výrobě a copyrightu jsou u
tištěných monografií přesunuty z minimálního
záznamu do doporučeného.
```
Z toho mi vychází, že původní šablona (pouze publication povinně) souhlasí se specifikací. Nicméně specifikace očekává data, která v některých případech není možné získat z minimálního MARC záznamu (poviný publication), resp. z MARC záznamu který je ve shodě se schválenou interpretací minimálního záznamu. 

Řešení jsou dvě:
 1. formálně správné, ale nepraktické - nechat to tak, validátor kontroluje MODS záznam a to, z čeho data vzešla (zde MARC21) ho striktně řečeno nemusí zajímat, a druhý odstavec je irelevantní protože zmiňuje jiný standard, resp. jeho podmnožinu.

 2. formálně nesprávné, asi praktické - zmíněná oprava, tedy mods:originInfo[@eventType='publication'] nepovinné, stejně jako verze s ostatními eventType a navíc extra pravidlo 
(Musí existovat alespoň jeden element originInfo a to s atributem eventType=publication nebo eventType=production). Nicméně takhle to bude další případ, kdy se formalizovaná verze specifikace, oproti které validuje validátor, rozchází s psanou specifikací.

**Comment by rzeh4n** [comment]
Takže zůstaneme u varianty 2 pro Monografie 1.2 a v další verzi standardu to bude formulováno přesněji.
