### ISSUE TITLE
WARNING na typ stranky u strukturalni mapy 

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/komplexni-validator#53]
Dobry den,
pri validaci nam validator (v. 1.6) nahlasil u Strukturalnich map Warning, ze ve fyzicke strukturalni mape je nepovolena hodnota atributu TYPE (index). Jde o stranky oznacene jako rejstrik.
Proc by mel byt problem, kdyz bude stranka oznacena jako rejstrik?

Dekuji

Ales Drahotussky

**Comment by godnat** [comment]
Souvisí s #42, bude se řešit.

**Comment by godnat** [comment]
hodnota index je povolená, validátor nechá projít hodnotu Index, protože je to tak v Pravidlech pro popis, ale v DMF se vyskytuje hodnota index. Hodnota index s malým i je správná, validátor se upraví tak, aby hodnotu index akceptoval.

**Comment by godnat** [comment]
Validátorem nyní projde hodnota "index" i hodnota "Index", preferovanou hodnotou je "index".  
Úprava je platná od další verze validátoru tj. 1.6.1 nebo 1.7.

Až se validátor upraví pro validaci dat dle nových DMF (monografie 1.3 a periodika 1.7), jedinou povolenou hodnotou bude "index" s malým i.

**Comment by rzeh4n** [comment]
Takže platí "Validátorem nyní projde hodnota "index", hodnota "Index" povede k varování."

Každopádně je špatně, že se DMF odkazuje na dokument _Pravidla pro popis periodik_, který je ale průběžně doplňován.
Např. v DMF Monografie 1.3 z ledna 2018 se na straně 92 uvádí:
> TYPE – bude se plnit typem stránky (dostupné v Pravidlech popisu pro monografie,
2012, dostupné na webu NDK)

Ten jsem na http://www.ndk.cz/standardy-digitalizace/metadata nenašel, pouze živou verzi 8 naposledy aktualizovanou v roce 2018. Standard by měl buď sám explicitně vyjmenovat povolené typy, anebo se odkazovat na konkrétní verzi externího dokumentu, která ale musí být dostupná.
Typ stránky se dál řeší na straně 22 (tady pro MODS záznamy) a opět se odkazuje na živý dokument.
