### ISSUE TITLE
ERROR ve validaci-nesprávná pravidla popisu záznamu?

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/komplexni-validator#54]
Dobrý den,
pri validaci knihy Regesten zur Geschichte des Herzogthums Troppau (1061-1464) (v SKC pod SYSNO 006752612), vyskocila chybove hlaseni, ze:
1) v elementu **recordInfo/descriptionStandard je** ocekavana hodnota rda a nikoliv AACR2
2)  chybí element **OriginInfo/ publication**

Zaznam knihy v SKC ma v sobe informaci, ze byl vytvoren podle AACR2. Nemuze byt problem v tom, ze zaznam mozna mohl vzniknou v tomto roce a validator tak automaticky ceka, ze zaznam ma byt dle RDA?

Dekuji

A. Drahotušský

**Comment by Drahotussky** [comment]
Toto Issues se muze smazat. Uz jsem na chybu prisel, doslo k ni na nasi strane.

**Comment by godnat** [comment]
Díky.
