### ISSUE TITLE
ERROR u elementu dateOther

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/komplexni-validator#55]
Dobry den,
pri validaci nam vyskocila chybova hlaska, ze zaznam neobsahuje element dateOther a issuance. Zaznam ale jiz obsahuje kompletni element OriginInfo se vsemi poli.
S panem Vaskem jsem v breznu vedl korespondenci o tomto problemu a bylo mi receno, ze opakovany vyskyt originInfo uz nemusi mit vsechna kompletni pole a nez se upravi validator, tak bude vyskakovat chyba.
Plati toto vyjadreni stale?
Dekuji

**Comment by PavlinaKocisova** [comment]
Dobrý den, ano, je to tak. Validátor zatím ještě neprošel potřebnými úpravami, proto chybné hlášky dosud vyskakují.

**Comment by rzeh4n** [comment]
Předpokládám, že tohle bylo opraveno ve verzi validátoru 1.7. Příště prosím uveďte verzi validátoru, DMF, oproti které bylo validováno, přesné znění chyby a ukázku problematického záznamu, nejlépe rovnou celý hlavní METS.

**Comment by isenkyr** [comment]
Validator v2.0, chybové hlášení Error: MODSMD_VOLUME_0001: /mods:mods/mods:originInfo[@eventType='manufacture']: nenalezen očekávaný povinný element 'mods:dateOther'
Tento element má být přítomen jen v případě výskytu podpole $c v poli 264. Viz standard pro monografie 1.2 strana 31. Proto by tento element měl být validován jako nepovinný jak je tomu uvedeno ve standardu. V příloze přikládám hlavní mets soubor.
[mets_lia001-0010wu.zip](https://github.com/NLCR/komplexni-validator/files/2987050/mets_lia001-0010wu.zip)

**Comment by godnat** [comment]
Upraveno, element dateOther je ve validátoru nyní nepovinný v souladu se standardy pro monografie verze 1.2, 1.3.1, 1.3.2

**Comment by isenkyr** [comment]
Dobrý den,

chci se zeptat jak by šel nyní nejlépe vyřešit problém s chybějícím elementem dateOther. Nyní používáme validátor v2.0, nevím jakou verzi validátoru použijí naši zákazníci, ale asi by nebylo dobré jim odevzdávat psp balíky, které nejsou validní. Chci se zeptat jestli je možné do elementu dateOther vepsat nějakou hodnotu, která nebude degradovat metadatový záznam a současně splní podmínky validace validátoru v2.0?

**Comment by godnat** [comment]
Dobrý den,

nová verze validátoru, kde bude dateOther nepovinný by měla vyjít v blízké době, nejpozději v průběhu dubna- stačilo by to takto? Případně můžete zákazníky odkázat na toto issue. 
Plnění elementu dateOther je krajní řešení, v případě potřeby se ale nad ním můžeme zamyslet.

**Comment by isenkyr** [comment]
Dobrý den,

pokud validátor vyjde v průběhu dubna tak počkáme na novou verzi. Děkuji
