### ISSUE TITLE
Změna povinnosti elementu mods:role v DMF pro monografie

### ISSUE THREAD

**Issue by godnat** [NLCR/komplexni-validator#58]
mods:role - povinnost elementu (M) v DMF pro monografie (ve všech verzích) neodpovídá požadavkům na minimální ani doporučený záznam RDA/MARC21 pro textové monografické zdroje. Úpravu povinnosti je potřeba vyřešit úpravou v DMF pro monografie i na straně validátoru.

**Comment by godnat** [comment]
Pokud validátor vypíše tuto chybu, je možné ji ignorovat. Absence elementu mods:role nebrání přijetí dat k dlouhodobému uložení. 

Povinnost elementu mods:role je snížena v DMF pro monografie verze 1.3, až se upraví validátor pro tuto verzi DMF nebude již absenci el. mods:role reportovat jako chybu.

**Comment by rzeh4n** [comment]
Povinnost elementu uvádí DMF, pro monografie je mods:role někdy povinný (M) a někdy nepovinný (MA). Pokud to chápu dobře, tak je nesoulad mezi DMF a "požadavky na RDF záznam", ale validátor správně reflektuje DMF. Změna pro stávající fDMF tedy není potřeba, upraveno to bude až v novém fDMF pro monografie 1.3 vzhledem ke změně v DMF pro monografie 1.3. Je to tak?

**Comment by godnat** [comment]
Ano je to tak, toto nastavení validátoru se měnit nebude. Necháváme v Issue, aby knihovny a dodavatelé věděli, že v tomto případě se nejedná u chybu dat a že data s takovou "chybou" přijmeme.

**Comment by rzeh4n** [comment]
Od Validátoru verze 2.0 a je pro DMF Monografie 1.3+ element mod:role vždy nepovinný. Resp. pokud někdy v budoucnu nenastane změna v některé novější DMF.
