### ISSUE TITLE
Kontrola názvové konvence PSP balíku (PSP_DIR_MATCHES_PSP_ID)

### ISSUE THREAD

**Issue by jbil7** [NLCR/komplexni-validator#63]
Při neshodě identifikátoru v názvu souboru (např. mets_a000227729.xml) s identifikátorem v názvu kořenového adresáře (např. abaXXX-000XXd) vypíše validátor varování s následujícím zněním: 

> checkFilenameMatchesPattern: název souboru abaXXX-000XXd neodpovídá vzoru [a000227729])

Vzhledem k závažnosti problému při pracování s daty a s ohledem na DMF (viz 6. bod, Názvová konvence složek a souborů) by se v případě neshodujících se identifikátorů v názvech součástí PSP balíku nemělo jednat o varování, ale o chybu.

**Comment by godnat** [comment]
Mělo by být upraveno v další verzi validátoru ještě tento rok,

**Comment by rzeh4n** [comment]
@godnat Takže mám to změnit pro všechna DMF z WARNING na ERROR?

**Comment by godnat** [comment]
Ne, jen pro ty nově přidávané specifikace a pro verzi 1.2 pro monografie a pro verzi 1.6 pro periodika. 

Pro verze 1.0 monografie a 1.4 periodika ponechat varování, protože ze specifikací tento požadavek na pojmenování nevyplývá jako jediný možný.

**Comment by rzeh4n** [comment]
Dоbře, opraveno pro stávající verze DMF a nové verze se budou odvozovat od DMF Monografie 1.2 a Periodika 1.6, takže to zůstane na ERROR.

**Comment by rzeh4n** [comment]
Tohle je relevantní zmíněnému pravidlu:
https://github.com/NLCR/Standard_NDK/issues/76
