### ISSUE TITLE
Color space -kontrolovaná hodnota nenalezena

### ISSUE THREAD

**Issue by godnat** [NLCR/komplexni-validator#64]
Validátor aktuálně reportuje jako chybu jiný barevný prostor/profil než "sRGB" a "grayscale". Tj. např. barevný profil "Adobe RGB" je pro validátor chyba. O chybu se ale nejedná, tento barevný profil je v pořádku, stejně jako několik dalších patřících do RGB barevných prostorů. Kontrola barevného prostoru bude ve validátoru dočasně zakomentována, protože tuto kontrolu provádí nástroj jpylyzer, který i na základě toho určí, zda je obraz validní či ne, stačí tedy, když validátor bude provádět kontrolu, že obraz prošel nástrojem jpylyzer jako validní. 
Úprava bude platná od další verze validátoru (tj. 1.6.1 nebo 1.7)

**Comment by rzeh4n** [comment]
Co jhove? Tam se to taky kontroluje:
``` 
       <validation name="Color space (1)">
            <xmlDataExtraction resultType="STRING">
                <firstNonempty>
                    <xpath>//j:property[j:name='EnumCS']/j:values/j:value</xpath>
                </firstNonempty>
            </xmlDataExtraction>
            <rules>
                <mustExist/>
                <!--povolene hodnoty "sRGB" nebo "greyscale"-->
                <mustMatchAny>
                    <constant>sRGB</constant>
                    <constant>Greyscale</constant>
                </mustMatchAny>
            </rules>
        </validation>
```

**Comment by godnat** [comment]
Tam by to taky chtělo úpravu, jen jsem uvažovala o složitější úpravě, protože v případě jhove se zakomentováním kontroly barevného prostoru přijde možná o kontrolu toho, zda se přijímá JP2 a ne JPX, kde je povoleno více hodnot. Ale zakomentuju to i tam nejspíš.
