### ISSUE TITLE
CLI - Chyba pojmenování xml souboru protokolu

### ISSUE THREAD

**Issue by volodymyrdn** [NLCR/komplexni-validator#65]
> --xml-protocol-dir <ADRESAR>  : Adresar pro ukladani xml protokolu s informacemi o validaci kazdeho PSP baliku. Nazev souboru protokolu je odvozen od nazvu PSP baliku a datumu+casu zacatku validace...

validátor pokouší vytvořit soubor s názvem ve tvaru *hh:mm:ss.xml. Dvojtečky není povolené v názvu souboru, proto validátor zahlásí chybu a xml soubor se neuloží.

**Comment by rzeh4n** [comment]
Opraveno od verze 2.0. Teď má soubor jméno stejně, jako při spuštění z GUI, tedy ROK_MESIC_DEN_HODINA_SEKUNDA_MINUTA_BALIK.xml, např. 2019_01_10_18_10_59_b50eb6b0-f0a4-11e3-b72e-005056827e52.xml
