### ISSUE TITLE
macOS verze nejde spustit

### ISSUE THREAD

**Issue by black23** [NLCR/komplexni-validator#66]
Poslední balíček se do systému sice nainstaluje korektně, ale spustit nejde = po spuštění se nestane nic. MacOS 10.13.3. Jsou nutné nějaké prerekvizity v systému? Kakadu mám.

**Comment by godnat** [comment]
Validátor se nespustí ani na verzi MacOs 10.12 (instalováno z pkg). 
Na verzi MacOs 10.12 se nám aktuálně daří spustit pouze validátor 1.6 instalovaný ze souboru dmg.

**Comment by black23** [comment]
Potvrzuji chování popsané @godnat i na MacOS 10.13.3. Spustit lze jen dmg instalace ve verzi 1.6.

**Comment by rzeh4n** [comment]
@black23 @godnat Můžete vyzkoušet instalátor pro verzi 2.1?

**Comment by black23** [comment]
Instalace funguje. Jen jsem zatím neměl čas projít instalaci všech podpůrných nástrojů.
