### ISSUE TITLE
Validátor pro verzi metadat 1.7.1 a 1.3.1

### ISSUE THREAD

**Issue by PavlinaDolezalova** [NLCR/komplexni-validator#67]
Dobrý den, kdy je v plánu zpřístupnit validátor pro verzi metadat 1.7.1 a 1.3.1?

**Comment by godnat** [comment]
Dobrý den,

očekáváme, že validátor pro validce dle DMF 1.7.1 a 1.3.1 bude zpřístupněn v roce 2018.

**Comment by PavlinaDolezalova** [comment]
Je tedy nyní vhodné generovat PSP balíky podle těchto nových verzí?

**Comment by godnat** [comment]
Ano je.

**Comment by rzeh4n** [comment]
Ve verzi 2.0 Validátoru byla přidána podpora pro:
- DMF Monografie 1.3
- DMF Monografie 1.3.1
- DMF Monografie 1.3.2
- DMF Periodika 1.7
- DMF Periodika 1.7.1
