### ISSUE TITLE
Jpylyzer 1.18.0 - 'Kontroluji dostupnost nástroje Jpylyzer: nenalezen (prázdný výstup)'

### ISSUE THREAD

**Issue by FoxKyong** [NLCR/komplexni-validator#69]
Tak validátor nějak nefunguje s Jpylyzerem verze 1.18.0. Když spustím validaci, tak to napíše:
```
Kontroluji dostupnost nástroje Jpylyzer: nenalezen (prázdný výstup)
```
To mi přišlo, že to ten jpylyzer nemůže nalézt, ale když jsem ho přejmenoval na jpylyzerx, tak to napsalo:
```
Kontroluji dostupnost nástroje Jpylyzer: nenalezen (Cannot run program "/home/radim/jpylyzer/jpylyzer": error=2, Adresář nebo soubor neexistuje)
```
Takže to znamená, že ho to nalezlo. Jpylyzer jsem zkoušel ručně spustit se vstupem nějakého JP2 a normálně fungoval, výpis verze 'jpylyzer --version' taky funguje, což je myslím to, co ten validátor při tom testu se snaží spustit a přitom to hlásí ten 'prázdný výstup'.

Testováno na Arch linuxu.

**Comment by godnat** [comment]
Zatím testováno jen na Windows 10, verze javy java 9.0.1:
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode), 

-v GUI i CLI byl Jpylyzer nalezen. Pro CLI byl použit následující příkaz:

java -jar KomplexniValidatorCLI-1.7.jar --config-dir C:/cesta/k/adresari/validatorConfig  --psp /cesta/k/adresari/psp/baliku --action VALIDATE_PSP --jpylyzer-path C:/cesta/k/adresari/nastroje/jpylyzer
 
Jakou máte verzi Javy?

**Comment by FoxKyong** [comment]
Tak verzi mám:
openjdk version "1.8.0_172"
OpenJDK Runtime Environment (build 1.8.0_172-b11)
OpenJDK 64-Bit Server VM (build 25.172-b11, mixed mode)

Devítkovou verzi jsem nezkoušel vzhledem k její živnostnosti 6 měsíců co má. Vyzkouším to teda ještě ve virtualu s novější verzí.

**Comment by rzeh4n** [comment]
Tak minimalne na Windows jpylyzer 1.18.0 spolupracuje s Validatorem korektne.

**Comment by rzeh4n** [comment]
Vyzkoušel jsem jpylyzer 1.18.0 pro Debian instalovaný z .deb z https://github.com/openpreserve/jpylyzer/releases/download/1.18.0/jpylyzer_1.18.0_amd64.deb
a taky v pořádku.

**Comment by rzeh4n** [comment]
Tak už nevím. 
Ještě bych zkusil _which jpylyzer_. Jestli ten domovský adresář je v pořádku, případně ho nenastavovat (jpylyzer.dir), stejně máte jpylyzer na path. Způsob spuštění a vyhodnocení všech nástrojů pro všechny platformy je definovaný v souboru imageUtils.xml v adresáři validatorConfig, vypadá nějak takhle:
https://github.com/NLCR/komplexni-validator/blob/master/sharedModule/src/main/resources/nkp/pspValidator/shared/validatorConfig/imageUtils.xml
Proměnná PATH se bere pro GUI ze souboru config.properties, který může vypadat nějak takto:
https://github.com/NLCR/komplexni-validator/blob/master/javaFxModule/src/main/resources/dev/config-linux.properties
a je součástí instalace. Anebo z parametru --jpylyzer-path pro spouštění přes CLI.
