### ISSUE TITLE
Element NonSort

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/komplexni-validator#71]
Pri validace validatoru ve verzi 1.6 nam validator hlasi WARNING, ze element **nonSort** je neocekavany. Jedna se o clen Der v nazvu titulu.
Znamena to, ze se ceka, ze se se nemecke cleny budou mazat v zaznamech?

Dekuji

Ales Drahotussky

**Comment by PavlinaKocisova** [comment]
Dobrý den, jedná se o to, že tento element nemáme  zastoupen v DMF, proto Vám validátor vydává varování. I s tímto elementem je ovšem balíček validní. Určitě tedy členy neodmazávejte. Ještě to otestujeme z hlediska LTP, ale nepředpokládáme problém.

**Comment by godnat** [comment]
Bylo ověřeno, že element nonSort nezpůsobí problém při vstupu do LTP NK.

**Comment by PavlinaKocisova** [comment]
Tento element bude formálně začleněn do DMF pro textové digitalizáty ve verzi 1.4 pro monografie a 1.8 pro periodika.
