### ISSUE TITLE
Přizpůsobení zvětšeného fontu rámečku

### ISSUE THREAD

**Issue by nezbedova** [NLCR/komplexni-validator#72]
Při nastavení středního fontu v systému windows se nepřizpůsobí rámeček a není vidět tlačítko Validovat.
![zobrazeni_stredni](https://user-images.githubusercontent.com/13831946/47208850-37844700-d38f-11e8-94b3-3315560e1c61.JPG)

**Comment by rzeh4n** [comment]
Opraveno pro zminene dialog, jeste proverit ostatni dialogy na vsech platformach, primarne Windows.
