### ISSUE TITLE
Nevalidní balíček kvůli copyright.status

### ISSUE THREAD

**Issue by volodymyrdn** [NLCR/komplexni-validator#73]
Dobrý den, 

Pokud hodnota atributu **copyright.status** v autorsko-pravních metadatech se rovná **Copyrighted**, validátor zahalasí chybu: 
 

> checkCopyrightMdIsValidByXsd: mets_aba010-000c0m.xml: RIGHTS_001: cvc-enumeration-valid: Value 'Copyrighted' is not facet-valid with respect to enumeration '[copyrighted, pd, pd_usfed, pd_holder, pd_expired, unknown]'. It must be a value from the enumeration.

Když tuto hodnotu změním na **copyrighted**  (což není podle standardu NDK, viz https://www.ndk.cz/standardy-digitalizace/DMFperiodika_16.pdf, str.č. 97), validátor zahlásí další chybu: 

> /mets:rightsMD/mets:mdWrap/mets:xmlData/cmd:copyright/@copyright.status: hodnota 'copyrighted' nesplňuje žádnou ze specifikací ["Copyrighted","pd","pd_expired","unknown"]

Je to projekt typu periodika 1.6. Mohli byste vyjádřit, která z hodnot je správná, a připadaně které změny je za potření udělat a ve kterých *.xsd souborech, aby validátor to validoval správně? Předem děkuji. 

S pozdravem V.Dyshchyn

**Comment by godnat** [comment]
Dobrý den,

podle schematu copyrightMD (https://www.cdlib.org/groups/rmg/) je správná hodnota 
 s malým písmenem, tj „copyrighted“, používejte tedy prosím tuto hodnotu. Ohledně úpravy xsd ještě dodáme informace.

**Comment by godnat** [comment]
Úprava v xsd se provede v souboru copyrightmd.xml na řádku 63 (cesta např. KomplexniValidatorGUI\app\validatorConfig\fDMF\periodical_1.6\techProfiles a KomplexniValidatorGUI\app\validatorConfig\fDMF\monograph_1.2\techProfiles), kde se hodnota "Copyrighted" nahradí hodnotou "copyrighted".

**Comment by rzeh4n** [comment]
Opraveno na "copyrighted" pro periodika 1.6 a monografie 1.2. Projeví se od verze Validátoru 2.0, případně se to dá řešit vlastní úpravou metadatového profilu (soubory _$CONFIG_DIR/fDMF/periodical_1.6/techProfiles/copyrightmd.xml_ a _$CONFIG_DIR/fDMF/monograph_1.2/techProfiles/copyrightmd.xml_)
