### ISSUE TITLE
marc21relators - odstranit "discontinued" hodnoty?

### ISSUE THREAD

**Issue by rzeh4n** [NLCR/komplexni-validator#74]
Všiml jsem si, že v slovníku povolených hodnot pro marc21 relators jsou některé hodnoty s pomlčkou. Tady je slovník validátoru:
https://github.com/NLCR/komplexni-validator/blob/master/sharedModule/src/main/resources/nkp/pspValidator/shared/validatorConfig/dictionaries/marcRelatorCodes.dict

a tady zdrojová data:
http://www.loc.gov/marc/relators/relacode.html
http://www.loc.gov/marc/relators/relaterm.html
Na stránce relacode.html se píše, že 

> Discontinued codes are included in this list. They are identified by a hyphen preceding the code. For example:

            -grt       Graphic technician

Těch pomlček jsem si dříve nevšiml, až teď, když jsem ten seznam seřadil kvůli zobrazeni v GUI. Jak se k tomu mám postavit? Buď by se měly ty hodnoty s pomlčkou smazat, anebo by se měly zachovat a tedy smazat pomlčky. Protože teď to validátor bere, že "**-grt**" a ne "**grt**" je jedna z povolených hodnot.

**Comment by isenkyr** [comment]
Podle mě by hodnoty začínající pomlčkou již neměly být používány a tudíž by neměly být součástí validátoru.  Na stránce http://www.loc.gov/marc/relators/relaterm.html jsou uvedené alternativy pro hodnoty z pomlčkou.
např.
-grt Graphic technician USE Artist
-clb Collaborator USE Contributor

**Comment by godnat** [comment]
Ty hodnoty s pomlčkou by se teď používat neměly, ale v minulosti se používaly, takže je možné, že v nějakých záznamech se vyskytovat budou a bude to dobře, protože tehdy povolené byly.  Takže za sebe se zatím spíše klaním jen k umazání těch pomlček. Ale ještě se poradíme s katalogizátory a prověříme transformační šablony, pokud by toto šablony řešily, pak by se daly ty zastaralé hodnoty smazat.

**Comment by godnat** [comment]
Katalogizátoři NK uváději, že v záznamech se určitě vyskytují dnes už neplatné kódy a transformační šablony toto neřeší, takže element s dnes neplatnou hodnotou se MODS může objevit. Proto pro následující verzi validátoru navrhuji odmazat jen ty pomlčky a hodnoty nechat.

**Comment by rzeh4n** [comment]
Dobře, změním to takto. 
Nicméně nemůžu se neohradit proti takovému řešení. Je to opět přístup "v datech jsme to našli nějak, tak podle toho změníme interpretaci standardu (Validátorem)". Tohle řešení naštěstí není v tak velkém rozporu se standardy DMF, protože ten seznam na https://www.loc.gov/marc/relators/relaterm.html není nijak verzovaný a dalo by se argumentovat, že když je kód třeba **grt** discontinued, tak v dřívejší verzi toho slovníku povolen byl.
Spíš si myslím, že právě tady by měl Validátor splnit svou roli a pokud se vytvoří PSP balík s daty z katalogu, kde je zastaralý a aktuálně neplatný kód relator, Validátor nahlásí chybu. A mělo by to vyústit v opravu buď transformace do PSP, nebo rovnou záznamu v katalogou, případně v ignorování výstupu Validátoru, každopádně ten problém v datech je nějak zachycen.

**Comment by godnat** [comment]
A v případě, že by zastaralé hodnoty byly z toho slovníku vymazány jednalo by se ve validátoru o chybu nebo o varování?

**Comment by rzeh4n** [comment]
Tak jde to dělat i warningem, i když to aktuálně v metadatových profilech nepoužíváme. Např. z:
https://github.com/NLCR/komplexni-validator/blob/master/sharedModule/src/main/resources/nkp/pspValidator/shared/validatorConfig/fDMF/monograph_1.2/biblioProfiles/mods/internalpart_chapter_rda.xml
Tady pokud se objeví něco jiného, než polžka ze slovníku, je výsledkem ERROR (protože _expectedContent_):
```xml
<element name="mods:roleTerm" mandatory="false">
    <expectedAttributes>
        <attribute name="type">
            <expectedContent>
                <value>code</value>
            </expectedContent>
        </attribute>

        <attribute name="authority">
            <expectedContent>
                <value>marcrelator</value>
            </expectedContent>
        </attribute>
    </expectedAttributes>
    <expectedContent>
        <fromDictionary name="marcRelatorCodes"/>
    </expectedContent>
</element>
```

Naopak z https://github.com/NLCR/komplexni-validator/blob/master/sharedModule/src/main/resources/nkp/pspValidator/shared/validatorConfig/fDMF/periodical_1.4/biblioProfiles/mods/supplement_aacr2.xml
Tady je hodnota ze slovníku jen doporučena, proto se vlastně nekontroluje nic (resp. jen, že tam není prázdná hodnota):
```xml
<element name="mods:roleTerm" mandatory="false">
    <expectedAttributes>
        <attribute name="type">
            <expectedContent>
                <value>code</value>
            </expectedContent>
        </attribute>

        <attribute name="authority" mandatory="false">
            <expectedContent>
                <!--kontrolovaný slovník marcRelatorCodes je jen doporučený-->
                <!--<value>marcrelator</value>-->
            </expectedContent>
        </attribute>
    </expectedAttributes>
    <expectedContent>
        <!--kontrolovaný slovník marcRelatorCodes je jen doporučený-->
        <!--<fromDictionary name="marcRelatorCodes"/>-->
    </expectedContent>
</element>
```
Nicméně (relativně) nově můžeme v metadatových profilech používat i _recommendedContent_, tam to funguje tak, že pokud hodnota nesedí, je výsledkem WARNING. Viz příklady:
https://github.com/NLCR/komplexni-validator/blob/master/sharedModule/src/main/resources/nkp/pspValidator/shared/validatorConfig/metadata_profile_example_mods.xml

Jenže s použitím _recommendedContent_ bude na tom **grt** stejně, jako **jakykolivDalsiNesmysl**. Nejde* to udělat tak, aby:
**abr** - OK
**grt** - WARING
**jakykolivDalsiNesmysl** - ERROR

A samozřejmě by se to muselo upravit na více místech, hodnota **fromDictionary name="marcRelatorCodes"** se aktuálně (Validátor 1.7 a 4 podporované DMF) používá na 45 místech.

*Šlo by to dodělat třeba tak, že by element/atribut měl buď _recommendedContent_, nebo _expectedContent_ + _toleratedContent_, přičemž pokud by hodnota byla z _expectedContent_, bylo by tok OK, pokud z _toleratedContent_, výsledkem by byl WARNING, jinak ERROR.

**Comment by rzeh4n** [comment]
Ještě jednou jsem se pořádně podíval na specifikace a vlastně je všude ta hodnota ze slovníku doporučená, stejně jako marcrelator pro autohority. Proto jsem všude změnil autoritu i hodnotu na recommendedContent, tudíž je WARNING při jakékoliv hodnotě mimo slovník, včetně "grt" apod.

**Comment by rzeh4n** [comment]
Takze ted vzdy WARNING pro vsechny hodnoty, co nejsou ze slovniku.
