### ISSUE TITLE
Validace atributu authority v elementu physicalDescription

### ISSUE THREAD

**Issue by isenkyr** [NLCR/komplexni-validator#84]
Dobrý den,
dnes jsem si stáhl validátor ve verzi 2.0 a zkoušel validovat PSP balík monografie ve verzi standardu 1.3.2. Validátor mi zahlásil chybu "MODSMD_VOLUME_0001: /mods:mods/mods:physicalDescription/mods:form[2]/@authority: hodnota 'marcform' nesplňuje žádnou ze specifikací ["rdamedia","rdacarrier"]". Marc záznam ze kterého pochází metadata je stažen ze Souborného katalogu NK a v záznamu je poznačeno, že byl pořízen podle rda. Problematice atributu "authority" v elementu "physicalDescription" se věnuje standard https://www.ndk.cz/standardy-digitalizace/dmf_monografie_1-3-2 na str.36. Chci se zeptat zda se jedná o chybu validátoru anebo hodnoty "marcform" atd nemohou být obsaženy v rda záznamu a měly by být smazány? V příloze uvádím zdrojový marcXml záznam ze souborného katalogu.
[cnb002904012_000001.zip](https://github.com/NLCR/komplexni-validator/files/2875472/cnb002904012_000001.zip)

**Comment by rzeh4n** [comment]
Dobrý den, Validátor kontroluje PSP/SIP balíček a neřeší konverzi z MARCu do PSP/SIP. Odkazovaný zip soubor obsahuje jen MARC záznam. Přiložte ještě, prosím, hlavní METS soubor z PSP/SIP balíčku.

**Comment by isenkyr** [comment]
Dobrý den,
připojuji hlavní mets.
[mets_aee001-0005k3.zip](https://github.com/NLCR/komplexni-validator/files/2879359/mets_aee001-0005k3.zip)

**Comment by godnat** [comment]
Dobrý den, hodnota "marcform" může být i v záznamu rda, přidáme ji jako povolenou hodnotu do validátoru. Specifikace to v poli form povoluje, ale u atributu authority už to zase vypadá,že pro rda záznamy povoluje jen "rdamedia" a "rdacarrier". Upravíme tedy ve validátoru a do specifikace přidáme jasnější informaci.

**Comment by isenkyr** [comment]
Jedná se tedy o validní mets soubor?

**Comment by MirkaBenackova** [comment]
Dobrý deň, áno, jedná sa o valídny mets.

**Comment by godnat** [comment]
Hodnoty "marcform", "marccategory", "marcsmd" budou přidány jako povolené u atributu "authority" elementu form. Úprava bude platná od verze validátoru 2.1. 
Ve standardech bude zpřesněna informace o jejich použití v případe rda záznamů.

**Comment by FilipPavcik** [comment]
Issue zatváram, keďže hore uvedené hodnoty boli pridané do validátora od verzie 2.1 i do novších verzií.
