### ISSUE TITLE
Stažení instalačních souborů

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/komplexni-validator#90]
Dobry den,
pouzivame pri instalaci validatoru **KomplexniValidatorGUI-v2.0_Windows_x64.exe**
Chtel bych se zeptat, zda je k tomuto souboru nutne stahnout vyhradne **KomplexniValidatorGUI-v2.0.zip** nebo to muze byt i **KomplexniValidatorCLI-2.0.zip**? 
Rozbalit se dany .zip ma  tam,kde je soubor .exe nebo je to jedno, kde v pocitaci .zip je?

Jeste by me zajimalo, zda je pri prechodu na vyssi verzi validatoru nutne nejdrive odinstalovat stavajici nebo staci nahradit soubor .exe a ostatni soubory za aktualni a pak spustit soubor .exe?

Dekuji
A.D.

**Comment by godnat** [comment]
Dobrý den,

chcete-li používat grafické rozhraní ve Windows, pak použijte:
**KomplexniValidatorGUI-v2.0_Windows_x64.exe**
nebo 
**KomplexniValidatorGUI-v2.0.zip**     -tato verze půjde spustit na 32bitové verzi Windows. 
Verze **KomplexniValidatorCLI-2.0.zip**  se pak ovládá přes příkazový řádek, tj. je bez grafického rozhraní. 

Instalátor **KomplexniValidatorGUI-v2.0_Windows_x64.exe** by měl obsahovat vše potřebné a nic by se k němu už instalovat nemělo (případně kromě nástrojů na kontrolu obrazů).  Napadá mě jestli nemáte náhodou problém s tím co se popisuje v issue #91?

**Comment by Drahotussky** [comment]
Dobry den,
dekuji za rady.
S tim problemem v issue 91 jsme se taky potykali.

Jeste bych rad pozadal o radu, kde najdu textovy log z validace? Prijde mi, ze se neulozi. Kdyz dam nazev souboru txt validovaneho balicku do vyhledavani,tak mi to nic nenajde.
Ani kdyz ve validatoru zvolim Zobrazit-Textovy log probehle validace

Dekuji

**Comment by godnat** [comment]
To vypadá na bug. Logy (textový i xml) by měly jít otevřít přímo z GUI po doběhnutí validace a zároveň se u předešlých verzí ukládaly do složky C:,\Users\[uzivatelske jmeno]\AppData\Local\KomplexniValidatorGUI\app\logs, tato složka ale u verze 2.0 pro Windows chybí.
