### ISSUE TITLE
Při instalaci z ..exe souboru je třeba manuálně zadat cestu k validatorConfig

### ISSUE THREAD

**Issue by godnat** [NLCR/komplexni-validator#91]
Při instalaci validátoru z **KomplexniValidatorGUI-v2.0_Windows_x64.exe** je nutné při prvním spuštění aplikace manuálně nastavit adresář s konfigurací validátoru, tj. navést do místa, kde se nachází validatorConfig. (u nás se nachází na tomto místě: C:\Users\[uživatelské jméno]\AppData\Local\KomplexniValidatorGUI\app

![image](https://user-images.githubusercontent.com/26278424/55012507-cef96000-4fe7-11e9-9a81-d128955fa701.png)

Není to moc uživatelsky přívětivé, je možné tento krok vypustit, aby validátor sám si tu složku validatorConfig našel bez manuálního zásahu? U verze validátoru 1.7 nebyl manuální zásah nutný.

**Comment by rzeh4n** [comment]
To je rozhodně chyba, ve verzi 2.1 by to mělo být opět bez nutnosti zadávat ručně. Problém může být i v pokusu o načtení konfigurace z některé starší verze Validátoru. 
Měl by to vyřešit následující postup:
- odinstalovat všechny předchozí verze Validátoru (ve Windows v Nastavení - Aplikace a funkce), tedy KomplexniValidatorGUI, PspValidator, PspValidatorGUI apod.
- Promazat vše, co neodstranil odinstalátor, tedy v adresáři C:\Users\UZIVATELSKE_JMENO\AppData\Local adresáře PspValidator, PspValidatorGUI, KomplexniValidator apod.
- nainstalovat poslední verzi Validátoru (od verze 2.1 dále) přes KomplexniValidatorGUI-2.1.exe

**Comment by rzeh4n** [comment]
Mělo by být opraveno ve verzi 2.1.
