### ISSUE TITLE
Neukládají se/nevytvářejí se logy z validace

### ISSUE THREAD

**Issue by godnat** [NLCR/komplexni-validator#92]
Z GUI u Komplexního validátoru ve verzi 2.0 pro Windows (možná i pro další OS) se neukládají textové ani xml logy z proběhlých validací. Nelze je zobrazit z GUI (přes Zobrazit --> Textový log proběhlé validace), ani se neukládají do složky logs (_C:\Users[uzivatelske jmeno]\AppData\Local\KomplexniValidatorGUI\app\logs_), složka úplně chybí. Obojí fungovalo u verze 1.7.

Zjištěno u aplikace instalované z **KomplexniValidatorGUI-v2.0_Windows_x64.exe**
 a **KomplexniValidatorGUI-v2.0.zip**. 

Obsah složky app u validátoru ve verzi 1.7:
![image](https://user-images.githubusercontent.com/26278424/55166777-0430ba00-5170-11e9-950a-f81e84c4293d.png)

Obsah složky app u validátoru ve verzi 2.0
![image](https://user-images.githubusercontent.com/26278424/55166823-17dc2080-5170-11e9-8927-1ea063468b88.png)

**Comment by rzeh4n** [comment]
Mělo by být opraveno ve verzi 2.1.

**Comment by Drahotussky** [comment]
Dobry den,
je ve verzi 2.1 opraveno nevytvareni logu?

Dekuji

A.D.

**Comment by godnat** [comment]
Dobrý den,

ano je to opraveno. V GUI verzi jsou logy dostupné po doběhnutí validace přes nabídku Zobrazit. Logy z validace jsou také dostupné ve složce k validátoru s názvem logs (např. C:\Users\[uzivatelsko jmeno]\AppData\Local\KomplexniValidatorGUI\app\logs)
