### ISSUE TITLE
Validace elementu subject se specifikaci msvkth

### ISSUE THREAD

**Issue by Drahotussky** [NLCR/komplexni-validator#93]
Dobry den,
pri validaci balicku vyskocilo varovani,ze u elementu subject neni specifikace msvkth jednou z definovanych.
Ve zmenach novych standardu je ale vyraz msvkth zarazen do povolenych hodnot

**Comment by godnat** [comment]
Dobrý den,

podle jaké verze DMF byla prováděna validace? Povolené msvkth jsem našla jen ve verzi DMF 1.3.2 a tak je to i teď povolené ve validátoru, takže balíčky dle DMF 1.3.2 by měly s msvkth projít. 

Hodnota msvkth není uvedena v DMF 1.7.1 a ani ve validátoru, zřejmě by ale měla být doplněna do specifikace, že?

**Comment by Drahotussky** [comment]
Dobry den,
jednalo se o balicky periodik podle standardu 1.7.1. Zapomne l jsem to uvest

**Comment by godnat** [comment]
Dobrý den,

je to pro vás aktuálně problém, když validátor dává varování? Data jsou s msvkth určitě v pořádku, ale teď hodnota msvkth není ve standardu, takže by to ve validátoru nemělo být (aby se udržel soulad validátoru se specifikací) ale správně by to v té specifikaci mělo být. Takže buď by se to teď opravilo ve validátoru (a tedy byl by nesoulad se specifikací) nebo by to zatím hlásilo varování a přidalo by se to do validátoru až s novou specifikací.

**Comment by jbil7** [comment]
Hodnota `msvkth` je v aktuální verzi Komplexního validátoru přítomna. Issue uzavírám.
