### ISSUE TITLE
Doplnit dokumentaci nástroje

### ISSUE THREAD

**Issue by godnat** [NLCR/komplexni-validator#97]
Je potřeba popsat např. jak probíhá vypínání validace některých sekcí, kam se ukládají logy apod. Případně i zapsat chyby, které se můžou vyskytnout (databázi chyb?)?

**Comment by rzeh4n** [comment]
Vypnutí validací přes GUI popsáno tady:
https://github.com/NLCR/komplexni-validator/wiki/Validace---GUI
